/**
 * anjosDatabase.js — Banco dos 72 Anjos Cabalísticos · Sistema Ars Akasha
 *
 * Fonte: 04-72-anjos-cabala/02-72-anjos-sagrados/ (fichas individuais) +
 *         tabela-consulta-anjo-por-data.md (datas de regência)
 *
 * Cada anjo cobre 5° do zodíaco — 72 × 5° = 360°.
 * Datas: cada anjo tem 5 dias de regência ao longo do ano.
 * Gênios da Humanidade: 5 dias especiais que sobrepõem qualquer anjo regular.
 */

// ─── Gênios da Humanidade ─────────────────────────────────────────────────────
// Nascidos nestas datas não têm anjo natal regular — pertencem à humanidade toda.
const GENIOS_DA_HUMANIDADE = [
  { dia: 5, mes: 1 },
  { dia: 19, mes: 3 },
  { dia: 31, mes: 5 },
  { dia: 12, mes: 8 },
  { dia: 24, mes: 10 },
];

// ─── Banco dos 72 Anjos ──────────────────────────────────────────────────────
const ANJOS_DB = [
  {
    numero: 1,
    nome: "Vehuiah",
    planeta: "Marte",
    signoZodiacal: "Áries",
    grauAbsolutoInicio: 0,
    grauAbsolutoFim: 5,
    datas: [{ dia: 1, mes: 6 }, { dia: 13, mes: 8 }, { dia: 20, mes: 3 }, { dia: 25, mes: 10 }, { dia: 6, mes: 1 }],
    hierarquia: "Coro 1 - Serafins",
    principeRegente: "Mettraton",
    daemonCorrespondente: "Baal",
    atributo: "Deus elevado e Exaltado por cima de todas as coisas",
    essencia: "Vontade",
    salmo: "3",
    horario: "00:00 Ã s 00:20",
  },
  {
    numero: 2,
    nome: "Jeliel",
    planeta: "JÃºpiter",
    signoZodiacal: "Áries",
    grauAbsolutoInicio: 5,
    grauAbsolutoFim: 10,
    datas: [{ dia: 2, mes: 6 }, { dia: 14, mes: 8 }, { dia: 21, mes: 3 }, { dia: 26, mes: 10 }, { dia: 7, mes: 1 }],
    hierarquia: "Coro 1 - Serafins",
    principeRegente: "Mettraton",
    daemonCorrespondente: "Agares",
    atributo: "Deus que socorre.",
    essencia: "MANANCIAL DE AMOR E ETERNA SABEDORIA.",
    salmo: "21",
    horario: "00:20 Ã s 00:40",
  },
  {
    numero: 3,
    nome: "Sitael",
    planeta: "Sol",
    signoZodiacal: "Áries",
    grauAbsolutoInicio: 10,
    grauAbsolutoFim: 15,
    datas: [{ dia: 3, mes: 6 }, { dia: 15, mes: 8 }, { dia: 22, mes: 3 }, { dia: 27, mes: 10 }, { dia: 8, mes: 1 }],
    hierarquia: "Coro 1 - Serafins",
    principeRegente: "Mettraton",
    daemonCorrespondente: "Vassago",
    atributo: "Deus esperança de todas as criaturas.",
    essencia: "VONTADE CONSTRUTORA.",
    salmo: "90",
    horario: "00:40 Ã s 01:00",
  },
  {
    numero: 4,
    nome: "Elemiah",
    planeta: "MercÃºrio",
    signoZodiacal: "Áries",
    grauAbsolutoInicio: 15,
    grauAbsolutoFim: 20,
    datas: [{ dia: 4, mes: 6 }, { dia: 16, mes: 8 }, { dia: 23, mes: 3 }, { dia: 28, mes: 10 }, { dia: 9, mes: 1 }],
    hierarquia: "Coro 1 - Serafins",
    principeRegente: "Mettraton",
    daemonCorrespondente: "Samigina",
    atributo: "Deus oculto.",
    essencia: "PODER DIVINO.",
    salmo: "6",
    horario: "01:00 Ã s 01:20",
  },
  {
    numero: 5,
    nome: "Mahasiah",
    planeta: "VÃªnus",
    signoZodiacal: "Áries",
    grauAbsolutoInicio: 20,
    grauAbsolutoFim: 25,
    datas: [{ dia: 5, mes: 6 }, { dia: 17, mes: 8 }, { dia: 24, mes: 3 }, { dia: 29, mes: 10 }, { dia: 10, mes: 1 }],
    hierarquia: "Coro 1 - Serafins",
    principeRegente: "Mettraton",
    daemonCorrespondente: "Marbas",
    atributo: "Deus salvador.",
    essencia: "VITRIOL.",
    salmo: "33",
    horario: "01:20 Ã s 01:40",
  },
  {
    numero: 6,
    nome: "Lelahel",
    planeta: "Sol",
    signoZodiacal: "Áries",
    grauAbsolutoInicio: 25,
    grauAbsolutoFim: 30,
    datas: [{ dia: 6, mes: 6 }, { dia: 18, mes: 8 }, { dia: 25, mes: 3 }, { dia: 30, mes: 10 }, { dia: 11, mes: 1 }],
    hierarquia: "Coro 1 - Serafins",
    principeRegente: "Mettraton",
    daemonCorrespondente: "Valefor",
    atributo: "Deus louvável.",
    essencia: "LUZ.",
    salmo: "9",
    horario: "01:40 Ã s 02:00",
  },
  {
    numero: 7,
    nome: "Achaiah",
    planeta: "MercÃºrio",
    signoZodiacal: "Touro",
    grauAbsolutoInicio: 30,
    grauAbsolutoFim: 35,
    datas: [{ dia: 7, mes: 6 }, { dia: 19, mes: 8 }, { dia: 26, mes: 3 }, { dia: 31, mes: 10 }, { dia: 12, mes: 1 }],
    hierarquia: "Coro 1 - Serafins",
    principeRegente: "Mettraton",
    daemonCorrespondente: "Amon",
    atributo: "Deus bom e paciente.",
    essencia: "PACIÊNCIA.",
    salmo: "102",
    horario: "02:00 Ã s 02:20",
  },
  {
    numero: 8,
    nome: "Cahethel",
    planeta: "Saturno",
    signoZodiacal: "Touro",
    grauAbsolutoInicio: 35,
    grauAbsolutoFim: 40,
    datas: [{ dia: 8, mes: 6 }, { dia: 20, mes: 8 }, { dia: 27, mes: 3 }, { dia: 1, mes: 11 }, { dia: 13, mes: 1 }],
    hierarquia: "Coro 1 - Serafins",
    principeRegente: "Mettraton",
    daemonCorrespondente: "Barbatos",
    atributo: "Deus adorável.",
    essencia: "BENÇÃO DE DEUS.",
    salmo: "94",
    horario: "02:20 Ã s 02:40",
  },
  {
    numero: 9,
    nome: "Haziel",
    planeta: "Lua",
    signoZodiacal: "Touro",
    grauAbsolutoInicio: 40,
    grauAbsolutoFim: 45,
    datas: [{ dia: 9, mes: 6 }, { dia: 21, mes: 8 }, { dia: 28, mes: 3 }, { dia: 2, mes: 11 }, { dia: 14, mes: 1 }],
    hierarquia: "Coro 2 - Querubins",
    principeRegente: "Ratziel.",
    daemonCorrespondente: "Paimon",
    atributo: "Deus de misericórdia.",
    essencia: "MISERICÓRDIA DE DEUS.",
    salmo: "24",
    horario: "02:40 Ã s 03:00",
  },
  {
    numero: 10,
    nome: "Aladiah",
    planeta: "JÃºpiter",
    signoZodiacal: "Touro",
    grauAbsolutoInicio: 45,
    grauAbsolutoFim: 50,
    datas: [{ dia: 10, mes: 6 }, { dia: 22, mes: 8 }, { dia: 29, mes: 3 }, { dia: 3, mes: 11 }, { dia: 15, mes: 1 }],
    hierarquia: "Coro 2 - Querubins",
    principeRegente: "Ratziel.",
    daemonCorrespondente: "Buer",
    atributo: "Deus propício.",
    essencia: "GRAÇA DIVINA.",
    salmo: "32",
    horario: "03:00 Ã s 03:20",
  },
  {
    numero: 11,
    nome: "Laoviah",
    planeta: "Saturno",
    signoZodiacal: "Touro",
    grauAbsolutoInicio: 50,
    grauAbsolutoFim: 55,
    datas: [{ dia: 11, mes: 6 }, { dia: 23, mes: 8 }, { dia: 30, mes: 3 }, { dia: 4, mes: 11 }, { dia: 16, mes: 1 }],
    hierarquia: "Coro 2 - Querubins",
    principeRegente: "Ratziel.",
    daemonCorrespondente: "Gusion",
    atributo: "Deus louvado e exaltado.",
    essencia: "VITÓRIA.",
    salmo: "17",
    horario: "03:20 Ã s 03:40",
  },
  {
    numero: 12,
    nome: "Hahaiah",
    planeta: "Netuno",
    signoZodiacal: "Touro",
    grauAbsolutoInicio: 55,
    grauAbsolutoFim: 60,
    datas: [{ dia: 12, mes: 6 }, { dia: 24, mes: 8 }, { dia: 31, mes: 3 }, { dia: 5, mes: 11 }, { dia: 17, mes: 1 }],
    hierarquia: "Coro 2 - Querubins",
    principeRegente: "Ratziel.",
    daemonCorrespondente: "Sitri",
    atributo: "Deus refúgio.",
    essencia: "REFÚGIO.",
    salmo: "9",
    horario: "03:40 Ã s 04:00",
  },
  {
    numero: 13,
    nome: "Yesalel",
    planeta: "Saturno",
    signoZodiacal: "Gêmeos",
    grauAbsolutoInicio: 60,
    grauAbsolutoFim: 65,
    datas: [{ dia: 13, mes: 6 }, { dia: 25, mes: 8 }, { dia: 1, mes: 4 }, { dia: 6, mes: 11 }, { dia: 18, mes: 1 }],
    hierarquia: "Coro 2 - Querubins",
    principeRegente: "Ratziel.",
    daemonCorrespondente: "Beleth",
    atributo: "Deus glorificado sobre todas as coisas.",
    essencia: "FIDELIDADE.",
    salmo: "97",
    horario: "04:00 Ã s 04:20",
  },
  {
    numero: 14,
    nome: "Mebahel",
    planeta: "JÃºpiter",
    signoZodiacal: "Gêmeos",
    grauAbsolutoInicio: 65,
    grauAbsolutoFim: 70,
    datas: [{ dia: 14, mes: 6 }, { dia: 26, mes: 8 }, { dia: 2, mes: 4 }, { dia: 7, mes: 11 }, { dia: 19, mes: 1 }],
    hierarquia: "Coro 2 - Querubins",
    principeRegente: "Ratziel.",
    daemonCorrespondente: "Leraje",
    atributo: "Deus conservador.",
    essencia: "VERDADE, LIBERDADE, JUSTIÇA.",
    salmo: "9",
    horario: "04:20 Ã s 04:40",
  },
  {
    numero: 15,
    nome: "Hariel",
    planeta: "Marte",
    signoZodiacal: "Gêmeos",
    grauAbsolutoInicio: 70,
    grauAbsolutoFim: 75,
    datas: [{ dia: 15, mes: 6 }, { dia: 27, mes: 8 }, { dia: 3, mes: 4 }, { dia: 8, mes: 11 }, { dia: 20, mes: 1 }],
    hierarquia: "Coro 2 - Querubins",
    principeRegente: "Ratziel.",
    daemonCorrespondente: "Eligos",
    atributo: "Deus criador.",
    essencia: "PURIFICAÇÃO.",
    salmo: "93",
    horario: "04:40 Ã s 05:00",
  },
  {
    numero: 16,
    nome: "Hacamiah",
    planeta: "Marte",
    signoZodiacal: "Gêmeos",
    grauAbsolutoInicio: 75,
    grauAbsolutoFim: 80,
    datas: [{ dia: 16, mes: 6 }, { dia: 28, mes: 8 }, { dia: 4, mes: 4 }, { dia: 9, mes: 11 }, { dia: 21, mes: 1 }],
    hierarquia: "Coro 2 - Querubins",
    principeRegente: "Ratziel.",
    daemonCorrespondente: "Zepar",
    atributo: "Deus que constrói o Universo.",
    essencia: "LEALDADE.",
    salmo: "87",
    horario: "5:00 Ã s 5:20",
  },
  {
    numero: 17,
    nome: "Lahuviah",
    planeta: "Sol",
    signoZodiacal: "Gêmeos",
    grauAbsolutoInicio: 80,
    grauAbsolutoFim: 85,
    datas: [{ dia: 17, mes: 6 }, { dia: 29, mes: 8 }, { dia: 5, mes: 4 }, { dia: 10, mes: 11 }, { dia: 22, mes: 1 }],
    hierarquia: "Coro 3 - Tronos",
    principeRegente: "Tsaphkiel.",
    daemonCorrespondente: "Botis",
    atributo: "Deus admirável.",
    essencia: "REVELAÇÃO.",
    salmo: "8",
    horario: "5:20 Ã s 5:40",
  },
  {
    numero: 18,
    nome: "Caliel",
    planeta: "MERCURIO.",
    signoZodiacal: "Gêmeos",
    grauAbsolutoInicio: 85,
    grauAbsolutoFim: 90,
    datas: [{ dia: 18, mes: 6 }, { dia: 30, mes: 8 }, { dia: 6, mes: 4 }, { dia: 11, mes: 11 }, { dia: 23, mes: 1 }],
    hierarquia: "Coro 3 - Tronos",
    principeRegente: "Tsaphkiel.",
    daemonCorrespondente: "Bathin",
    atributo: "Deus pronto a acolher.",
    essencia: "JUSTIÇA.",
    salmo: "7",
    horario: "5:40 Ã s 6:00",
  },
  {
    numero: 19,
    nome: "Leuviah",
    planeta: "VÃªnus",
    signoZodiacal: "Câncer",
    grauAbsolutoInicio: 90,
    grauAbsolutoFim: 95,
    datas: [{ dia: 19, mes: 6 }, { dia: 31, mes: 8 }, { dia: 7, mes: 4 }, { dia: 12, mes: 11 }, { dia: 24, mes: 1 }],
    hierarquia: "Coro 3 - Tronos",
    principeRegente: "Tsaphkiel.",
    daemonCorrespondente: "Saleos",
    atributo: "Deus que acolhe os pecadores.",
    essencia: "INTELIGÊNCIA EXPANSIVA OU FRUTIFICANTE.",
    salmo: "39",
    horario: "6:00 Ã s 6:20",
  },
  {
    numero: 20,
    nome: "Pahaliah",
    planeta: "Lua",
    signoZodiacal: "Câncer",
    grauAbsolutoInicio: 95,
    grauAbsolutoFim: 100,
    datas: [{ dia: 20, mes: 6 }, { dia: 1, mes: 9 }, { dia: 8, mes: 4 }, { dia: 13, mes: 11 }, { dia: 25, mes: 1 }],
    hierarquia: "Coro 3 - Tronos",
    principeRegente: "Tsaphkiel.",
    daemonCorrespondente: "Purson",
    atributo: "Deus redentor.",
    essencia: "REDENÇÃO.",
    salmo: "119",
    horario: "6:20 Ã s 6:40",
  },
  {
    numero: 21,
    nome: "Nelchael",
    planeta: "MercÃºrio",
    signoZodiacal: "Câncer",
    grauAbsolutoInicio: 100,
    grauAbsolutoFim: 105,
    datas: [{ dia: 21, mes: 6 }, { dia: 2, mes: 9 }, { dia: 9, mes: 4 }, { dia: 14, mes: 11 }, { dia: 26, mes: 1 }],
    hierarquia: "Coro 3 - Tronos",
    principeRegente: "Tsaphkiel.",
    daemonCorrespondente: "Marax",
    atributo: "Deus só e único.",
    essencia: "AFÃ DE APRENDER.",
    salmo: "30",
    horario: "6:40 Ã s 7:00",
  },
  {
    numero: 22,
    nome: "Yeiaiel",
    planeta: "MercÃºrio",
    signoZodiacal: "Câncer",
    grauAbsolutoInicio: 105,
    grauAbsolutoFim: 110,
    datas: [{ dia: 22, mes: 6 }, { dia: 3, mes: 9 }, { dia: 10, mes: 4 }, { dia: 15, mes: 11 }, { dia: 27, mes: 1 }],
    hierarquia: "Coro 3 - Tronos",
    principeRegente: "Tsaphkiel.",
    daemonCorrespondente: "Ipos",
    atributo: "A justiça de Deus.",
    essencia: "RENOME.",
    salmo: "120",
    horario: "7:00 Ã s 7:20",
  },
  {
    numero: 23,
    nome: "Melahel",
    planeta: "Lua",
    signoZodiacal: "Câncer",
    grauAbsolutoInicio: 110,
    grauAbsolutoFim: 115,
    datas: [{ dia: 23, mes: 6 }, { dia: 4, mes: 9 }, { dia: 11, mes: 4 }, { dia: 16, mes: 11 }, { dia: 28, mes: 1 }],
    hierarquia: "Coro 3 - Tronos",
    principeRegente: "Tsaphkiel.",
    daemonCorrespondente: "Aim",
    atributo: "Deus que livra dos males.",
    essencia: "CAPACIDADE CURADORA.",
    salmo: "120",
    horario: "7:20 Ã s 7:40",
  },
  {
    numero: 24,
    nome: "Haheuiah",
    planeta: "VÃªnus",
    signoZodiacal: "Câncer",
    grauAbsolutoInicio: 115,
    grauAbsolutoFim: 120,
    datas: [{ dia: 24, mes: 6 }, { dia: 5, mes: 9 }, { dia: 12, mes: 4 }, { dia: 17, mes: 11 }, { dia: 29, mes: 1 }],
    hierarquia: "Coro 3 - Tronos",
    principeRegente: "Tsaphkiel.",
    daemonCorrespondente: "Naberius",
    atributo: "Deus bom por si mesmo.",
    essencia: "PROTEÇÃO (Cidade refúgio - rigores da Lei dos homens).",
    salmo: "32",
    horario: "7:40 Ã s 8:00",
  },
  {
    numero: 25,
    nome: "Nithhaiah",
    planeta: "Saturno",
    signoZodiacal: "Leão",
    grauAbsolutoInicio: 120,
    grauAbsolutoFim: 125,
    datas: [{ dia: 25, mes: 6 }, { dia: 6, mes: 9 }, { dia: 13, mes: 4 }, { dia: 18, mes: 11 }, { dia: 30, mes: 1 }],
    hierarquia: "Coro 4 - Dominacoes",
    principeRegente: "Tzadkiel.",
    daemonCorrespondente: "Glasya-Labolas",
    atributo: "Deus que dá a sabedoria.",
    essencia: "SABEDORIA.",
    salmo: "9",
    horario: "8:00 Ã s 8:20",
  },
  {
    numero: 26,
    nome: "Haaiah",
    planeta: "Lua",
    signoZodiacal: "Leão",
    grauAbsolutoInicio: 125,
    grauAbsolutoFim: 130,
    datas: [{ dia: 26, mes: 6 }, { dia: 7, mes: 9 }, { dia: 14, mes: 4 }, { dia: 19, mes: 11 }, { dia: 31, mes: 1 }],
    hierarquia: "Coro 4 - Dominacoes",
    principeRegente: "Tzadkiel.",
    daemonCorrespondente: "Bune",
    atributo: "Deus oculto.",
    essencia: "CIÊNCIA POLÍTICA.",
    salmo: "118",
    horario: "8:20 Ã s 8:40",
  },
  {
    numero: 27,
    nome: "Ierathel",
    planeta: "Saturno",
    signoZodiacal: "Leão",
    grauAbsolutoInicio: 130,
    grauAbsolutoFim: 135,
    datas: [{ dia: 27, mes: 6 }, { dia: 8, mes: 9 }, { dia: 15, mes: 4 }, { dia: 20, mes: 11 }, { dia: 1, mes: 2 }],
    hierarquia: "Coro 4 - Dominacoes",
    principeRegente: "Tzadkiel.",
    daemonCorrespondente: "Ronove",
    atributo: "Deus punidor dos maus.",
    essencia: "PROPAGAÇÃO DE LUZ, DA CIVILIZAÇÃO, DA LIBERDADE.",
    salmo: "139",
    horario: "8:40 Ã s 9:00",
  },
  {
    numero: 28,
    nome: "Seheiah",
    planeta: "JÃºpiter",
    signoZodiacal: "Leão",
    grauAbsolutoInicio: 135,
    grauAbsolutoFim: 140,
    datas: [{ dia: 28, mes: 6 }, { dia: 9, mes: 9 }, { dia: 16, mes: 4 }, { dia: 21, mes: 11 }, { dia: 2, mes: 2 }],
    hierarquia: "Coro 4 - Dominacoes",
    principeRegente: "Tzadkiel.",
    daemonCorrespondente: "Berith",
    atributo: "Deus que cura os enfermos.",
    essencia: "LONGEVIDADE.",
    salmo: "70",
    horario: "9:00 Ã s 9:20",
  },
  {
    numero: 29,
    nome: "Reyel",
    planeta: "Marte",
    signoZodiacal: "Leão",
    grauAbsolutoInicio: 140,
    grauAbsolutoFim: 145,
    datas: [{ dia: 29, mes: 6 }, { dia: 10, mes: 9 }, { dia: 17, mes: 4 }, { dia: 22, mes: 11 }, { dia: 3, mes: 2 }],
    hierarquia: "Coro 4 - Dominacoes",
    principeRegente: "Tzadkiel.",
    daemonCorrespondente: "Astaroth",
    atributo: "Deus pronto a socorrer.",
    essencia: "LIBERTAÇÃO.",
    salmo: "53",
    horario: "9:20 Ã s 9:40",
  },
  {
    numero: 30,
    nome: "Omael",
    planeta: "Sol",
    signoZodiacal: "Leão",
    grauAbsolutoInicio: 145,
    grauAbsolutoFim: 150,
    datas: [{ dia: 30, mes: 6 }, { dia: 11, mes: 9 }, { dia: 18, mes: 4 }, { dia: 23, mes: 11 }, { dia: 4, mes: 2 }],
    hierarquia: "Coro 4 - Dominacoes",
    principeRegente: "Tzadkiel.",
    daemonCorrespondente: "Forneus",
    atributo: "Deus paciente.",
    essencia: "MULTIPLICAÇÃO.",
    salmo: "70",
    horario: "9:40 Ã s 10:00",
  },
  {
    numero: 31,
    nome: "Lecabel",
    planeta: "Sol",
    signoZodiacal: "Virgem",
    grauAbsolutoInicio: 151,
    grauAbsolutoFim: 156,
    datas: [{ dia: 1, mes: 7 }, { dia: 12, mes: 9 }, { dia: 19, mes: 4 }, { dia: 24, mes: 11 }, { dia: 5, mes: 2 }],
    hierarquia: "Coro 4 - Dominacoes",
    principeRegente: "Tzadkiel.",
    daemonCorrespondente: "Foras",
    atributo: "Deus que inspira.",
    essencia: "TALENTO RESOLUTIVO.",
    salmo: "70",
    horario: "10:00 Ã s 10:20",
  },
  {
    numero: 32,
    nome: "Vassahiah",
    planeta: "MercÃºrio",
    signoZodiacal: "Virgem",
    grauAbsolutoInicio: 155,
    grauAbsolutoFim: 160,
    datas: [{ dia: 2, mes: 7 }, { dia: 13, mes: 9 }, { dia: 20, mes: 4 }, { dia: 25, mes: 11 }, { dia: 6, mes: 2 }],
    hierarquia: "Coro 4 - Dominacoes",
    principeRegente: "Tzadkiel",
    daemonCorrespondente: "Asmoday",
    atributo: "Deus justo.",
    essencia: "CLEMÊNCIA.",
    salmo: "32",
    horario: "10:20 Ã s 10:40",
  },
  {
    numero: 33,
    nome: "Yehuiah",
    planeta: "Lua",
    signoZodiacal: "Virgem",
    grauAbsolutoInicio: 160,
    grauAbsolutoFim: 165,
    datas: [{ dia: 3, mes: 7 }, { dia: 14, mes: 9 }, { dia: 21, mes: 4 }, { dia: 26, mes: 11 }, { dia: 7, mes: 2 }],
    hierarquia: "Coro 5 - Potencias",
    principeRegente: "Camael.",
    daemonCorrespondente: "Gaap",
    atributo: "Deus que conhece todas as coisas.",
    essencia: "SUBORDINAÇÃO.",
    salmo: "33",
    horario: "10:40 Ã s 11:00",
  },
  {
    numero: 34,
    nome: "Lehahiah",
    planeta: "Saturno",
    signoZodiacal: "Virgem",
    grauAbsolutoInicio: 165,
    grauAbsolutoFim: 170,
    datas: [{ dia: 4, mes: 7 }, { dia: 15, mes: 9 }, { dia: 22, mes: 4 }, { dia: 27, mes: 11 }, { dia: 8, mes: 2 }],
    hierarquia: "Coro 5 - Potencias",
    principeRegente: "Camael.",
    daemonCorrespondente: "Furfur",
    atributo: "Deus clemente.",
    essencia: "OBEDIÊNCIA. inteligência.",
    salmo: "130",
    horario: "11:00 Ã s 11:20",
  },
  {
    numero: 35,
    nome: "Chavahiah",
    planeta: "MercÃºrio",
    signoZodiacal: "Virgem",
    grauAbsolutoInicio: 170,
    grauAbsolutoFim: 175,
    datas: [{ dia: 5, mes: 7 }, { dia: 16, mes: 9 }, { dia: 23, mes: 4 }, { dia: 28, mes: 11 }, { dia: 9, mes: 2 }],
    hierarquia: "Coro 5 - Potencias",
    principeRegente: "Camael.",
    daemonCorrespondente: "Marchosias",
    atributo: "Deus que dá a alegria.",
    essencia: "RECONCILIAÇÃO.",
    salmo: "114",
    horario: "11:20 Ã s 11:40",
  },
  {
    numero: 36,
    nome: "Menadel",
    planeta: "Marte",
    signoZodiacal: "Virgem",
    grauAbsolutoInicio: 175,
    grauAbsolutoFim: 180,
    datas: [{ dia: 6, mes: 7 }, { dia: 17, mes: 9 }, { dia: 24, mes: 4 }, { dia: 29, mes: 11 }, { dia: 10, mes: 2 }],
    hierarquia: "Coro 5 - Potencias",
    principeRegente: "Camael.",
    daemonCorrespondente: "Stolas",
    atributo: "Deus adorável.",
    essencia: "TRABALHO.",
    salmo: "25",
    horario: "11:40 Ã s 12:00",
  },
  {
    numero: 37,
    nome: "Aniel",
    planeta: "Lua",
    signoZodiacal: "Libra",
    grauAbsolutoInicio: 180,
    grauAbsolutoFim: 185,
    datas: [{ dia: 7, mes: 7 }, { dia: 18, mes: 9 }, { dia: 25, mes: 4 }, { dia: 30, mes: 11 }, { dia: 11, mes: 2 }],
    hierarquia: "Coro 5 - Potencias",
    principeRegente: "Camael.",
    daemonCorrespondente: "Phenex",
    atributo: "Deus nas virtudes.",
    essencia: "RUPTURA DO CERCO.",
    salmo: "79",
    horario: "12:00 Ã s 12:20",
  },
  {
    numero: 38,
    nome: "Haamiah",
    planeta: "Saturno",
    signoZodiacal: "Libra",
    grauAbsolutoInicio: 185,
    grauAbsolutoFim: 190,
    datas: [{ dia: 8, mes: 7 }, { dia: 19, mes: 9 }, { dia: 26, mes: 4 }, { dia: 1, mes: 12 }, { dia: 12, mes: 2 }],
    hierarquia: "Coro 5 - Potencias",
    principeRegente: "Camael.",
    daemonCorrespondente: "Halphas",
    atributo: "Deus, a esperança de todos os filhos da terra.",
    essencia: "RITUAL.",
    salmo: "90",
    horario: "12:20 Ã s 12:40",
  },
  {
    numero: 39,
    nome: "Rehael",
    planeta: "Saturno",
    signoZodiacal: "Libra",
    grauAbsolutoInicio: 190,
    grauAbsolutoFim: 195,
    datas: [{ dia: 9, mes: 7 }, { dia: 20, mes: 9 }, { dia: 27, mes: 4 }, { dia: 2, mes: 12 }, { dia: 13, mes: 2 }],
    hierarquia: "Coro 5 - Potencias",
    principeRegente: "Camael.",
    daemonCorrespondente: "Malphas",
    atributo: "Deus que acolhe os pecadores.",
    essencia: "SUBMISSÃO FILIAL.",
    salmo: "29",
    horario: "12:40 Ã s 13:00",
  },
  {
    numero: 40,
    nome: "Yeiazel",
    planeta: "MercÃºrio",
    signoZodiacal: "Libra",
    grauAbsolutoInicio: 195,
    grauAbsolutoFim: 200,
    datas: [{ dia: 10, mes: 7 }, { dia: 21, mes: 9 }, { dia: 28, mes: 4 }, { dia: 3, mes: 12 }, { dia: 14, mes: 2 }],
    hierarquia: "Coro 5 - Potencias",
    principeRegente: "Camael.",
    daemonCorrespondente: "Raum",
    atributo: "Deus que regozija, que dá alegria.",
    essencia: "CONSOLO OU REGOZIJO.",
    salmo: "87",
    horario: "13:00 Ã s 13:20",
  },
  {
    numero: 41,
    nome: "Hahael",
    planeta: "JÃºpiter",
    signoZodiacal: "Libra",
    grauAbsolutoInicio: 200,
    grauAbsolutoFim: 205,
    datas: [{ dia: 11, mes: 7 }, { dia: 22, mes: 9 }, { dia: 29, mes: 4 }, { dia: 4, mes: 12 }, { dia: 15, mes: 2 }],
    hierarquia: "Coro 6 - Virtudes",
    principeRegente: "Michael.",
    daemonCorrespondente: "Focalor",
    atributo: "Deus em três pessoas.",
    essencia: "SACERDÓCIO.",
    salmo: "119",
    horario: "13:20 Ã s 13:40",
  },
  {
    numero: 42,
    nome: "Micael",
    planeta: "MercÃºrio",
    signoZodiacal: "Libra",
    grauAbsolutoInicio: 205,
    grauAbsolutoFim: 210,
    datas: [{ dia: 12, mes: 7 }, { dia: 23, mes: 9 }, { dia: 30, mes: 4 }, { dia: 5, mes: 12 }, { dia: 16, mes: 2 }],
    hierarquia: "Coro 6 - Virtudes",
    principeRegente: "Michael.",
    daemonCorrespondente: "Vepar",
    atributo: "Virtude de Deus, casa de Deus, semelhante a Deus.",
    essencia: "ORDEM POLÍTICA.",
    salmo: "120",
    horario: "13:40 Ã s 14:00",
  },
  {
    numero: 43,
    nome: "Veuliah",
    planeta: "Marte",
    signoZodiacal: "Libra",
    grauAbsolutoInicio: 180,
    grauAbsolutoFim: 185,
    datas: [{ dia: 13, mes: 7 }, { dia: 24, mes: 9 }, { dia: 1, mes: 5 }, { dia: 6, mes: 12 }, { dia: 17, mes: 2 }],
    hierarquia: "Coro 6 - Virtudes",
    principeRegente: "Michael.",
    daemonCorrespondente: "Sabnock",
    atributo: "Rei dominador.",
    essencia: "PROSPERIDADE.",
    salmo: "87",
    horario: "14:00 Ã s 14:20",
  },
  {
    numero: 44,
    nome: "Yelaiah",
    planeta: "MercÃºrio",
    signoZodiacal: "Escorpião",
    grauAbsolutoInicio: 215,
    grauAbsolutoFim: 220,
    datas: [{ dia: 14, mes: 7 }, { dia: 25, mes: 9 }, { dia: 2, mes: 5 }, { dia: 7, mes: 12 }, { dia: 18, mes: 2 }],
    hierarquia: "Coro 6 - Virtudes",
    principeRegente: "Michael.",
    daemonCorrespondente: "Shax",
    atributo: "Deus Eterno.",
    essencia: "TALENTO MILITAR.",
    salmo: "118",
    horario: "14:20 Ã s 14:40",
  },
  {
    numero: 45,
    nome: "Sehaliah",
    planeta: "Sol",
    signoZodiacal: "Escorpião",
    grauAbsolutoInicio: 220,
    grauAbsolutoFim: 225,
    datas: [{ dia: 15, mes: 7 }, { dia: 26, mes: 9 }, { dia: 3, mes: 5 }, { dia: 8, mes: 12 }, { dia: 19, mes: 2 }],
    hierarquia: "Coro 6 - Virtudes",
    principeRegente: "Michael.",
    daemonCorrespondente: "Vine",
    atributo: "Motor de todas as coisas.",
    essencia: "Motor (Equilíbrio - 4 elementos).",
    salmo: "93",
    horario: "14:40 Ã s 15:00",
  },
  {
    numero: 46,
    nome: "Ariel",
    planeta: "Saturno",
    signoZodiacal: "Escorpião",
    grauAbsolutoInicio: 225,
    grauAbsolutoFim: 230,
    datas: [{ dia: 16, mes: 7 }, { dia: 27, mes: 9 }, { dia: 4, mes: 5 }, { dia: 9, mes: 12 }, { dia: 20, mes: 2 }],
    hierarquia: "Coro 6 - Virtudes",
    principeRegente: "Michael.",
    daemonCorrespondente: "Bifrons",
    atributo: "Deus revelador.",
    essencia: "PERCEPÇÃO REVELADORA.",
    salmo: "144",
    horario: "15:00 Ã s 15:20",
  },
  {
    numero: 47,
    nome: "Assaliah",
    planeta: "VÃªnus",
    signoZodiacal: "Escorpião",
    grauAbsolutoInicio: 230,
    grauAbsolutoFim: 235,
    datas: [{ dia: 17, mes: 7 }, { dia: 28, mes: 9 }, { dia: 5, mes: 5 }, { dia: 10, mes: 12 }, { dia: 21, mes: 2 }],
    hierarquia: "Coro 6 - Virtudes",
    principeRegente: "Michael.",
    daemonCorrespondente: "Vual",
    atributo: "Deus justo que indica a Verdade.",
    essencia: "CONTEMPLAÇÃO.",
    salmo: "103",
    horario: "15:20 Ã s 15:40",
  },
  {
    numero: 48,
    nome: "Mihael",
    planeta: "VÃªnus",
    signoZodiacal: "Escorpião",
    grauAbsolutoInicio: 235,
    grauAbsolutoFim: 240,
    datas: [{ dia: 18, mes: 7 }, { dia: 29, mes: 9 }, { dia: 6, mes: 5 }, { dia: 11, mes: 12 }, { dia: 22, mes: 2 }],
    hierarquia: "Coro 6 - Virtudes",
    principeRegente: "Michael.",
    daemonCorrespondente: "Hagenti",
    atributo: "Deus, Pai que socorre.",
    essencia: "GERAÇÃO.",
    salmo: "97",
    horario: "15:40 Ã s 16:00",
  },
  {
    numero: 49,
    nome: "Vehuel",
    planeta: "MercÃºrio",
    signoZodiacal: "Sagitário",
    grauAbsolutoInicio: 240,
    grauAbsolutoFim: 245,
    datas: [{ dia: 19, mes: 7 }, { dia: 30, mes: 9 }, { dia: 7, mes: 5 }, { dia: 12, mes: 12 }, { dia: 23, mes: 2 }],
    hierarquia: "Coro 7 - Principados",
    principeRegente: "Haniel.",
    daemonCorrespondente: "Crocell",
    atributo: "Deus grande e elevado.",
    essencia: "ELEVAÇÃO OU GRANDEZA.",
    salmo: "144",
    horario: "16:00 Ã s 16:20",
  },
  {
    numero: 50,
    nome: "Daniel",
    planeta: "Lua",
    signoZodiacal: "Sagitário",
    grauAbsolutoInicio: 245,
    grauAbsolutoFim: 250,
    datas: [{ dia: 20, mes: 7 }, { dia: 1, mes: 10 }, { dia: 8, mes: 5 }, { dia: 13, mes: 12 }, { dia: 24, mes: 2 }],
    hierarquia: "Coro 7 - Principados",
    principeRegente: "Haniel.",
    daemonCorrespondente: "Furcas",
    atributo: "O Signo das Misericórdias, o Anjo das Confissões.",
    essencia: "ELOQUÊNCIA.",
    salmo: "102",
    horario: "16:20 Ã s 16:40",
  },
  {
    numero: 51,
    nome: "Hahassiah",
    planeta: "Lua",
    signoZodiacal: "Sagitário",
    grauAbsolutoInicio: 250,
    grauAbsolutoFim: 255,
    datas: [{ dia: 21, mes: 7 }, { dia: 2, mes: 10 }, { dia: 9, mes: 5 }, { dia: 14, mes: 12 }, { dia: 25, mes: 2 }],
    hierarquia: "Coro 7 - Principados",
    principeRegente: "Haniel.",
    daemonCorrespondente: "Balam",
    atributo: "Deus oculto.",
    essencia: "MEDICINA UNIVERSAL OU PEDRA FILOSOFAL.",
    salmo: "103",
    horario: "16:40 Ã s 17:00",
  },
  {
    numero: 52,
    nome: "Ymamiah",
    planeta: "JÃºpiter",
    signoZodiacal: "Sagitário",
    grauAbsolutoInicio: 255,
    grauAbsolutoFim: 260,
    datas: [{ dia: 22, mes: 7 }, { dia: 3, mes: 10 }, { dia: 10, mes: 5 }, { dia: 15, mes: 12 }, { dia: 26, mes: 2 }],
    hierarquia: "Coro 7 - Principados",
    principeRegente: "Haniel.",
    daemonCorrespondente: "Alloces",
    atributo: "Deus elevado acima de todas as coisas.",
    essencia: "EXPIAÇÃO DOS ERROS.",
    salmo: "7",
    horario: "17:00 Ã s 17:20",
  },
  {
    numero: 53,
    nome: "Nanael",
    planeta: "Saturno",
    signoZodiacal: "Sagitário",
    grauAbsolutoInicio: 260,
    grauAbsolutoFim: 265,
    datas: [{ dia: 23, mes: 7 }, { dia: 4, mes: 10 }, { dia: 11, mes: 5 }, { dia: 16, mes: 12 }, { dia: 27, mes: 2 }],
    hierarquia: "Coro 7 - Principados",
    principeRegente: "Haniel.",
    daemonCorrespondente: "Camio",
    atributo: "Deus que humilha os orgulhosos.",
    essencia: "COMUNICAÇÃO ESPIRITUAL.",
    salmo: "118",
    horario: "17:20 Ã s 17:40",
  },
  {
    numero: 54,
    nome: "Nithael",
    planeta: "JÃºpiter",
    signoZodiacal: "Sagitário",
    grauAbsolutoInicio: 265,
    grauAbsolutoFim: 270,
    datas: [{ dia: 24, mes: 7 }, { dia: 5, mes: 10 }, { dia: 12, mes: 5 }, { dia: 17, mes: 12 }, { dia: 29, mes: 2 }],
    hierarquia: "Coro 7 - Principados",
    principeRegente: "Haniel.",
    daemonCorrespondente: "Murmur",
    atributo: "Rei dos céus.",
    essencia: "LEGITIMIDADE SUCESSORA.",
    salmo: "102",
    horario: "17:40 Ã s 18:00",
  },
  {
    numero: 55,
    nome: "Mebahiah",
    planeta: "JÃºpiter",
    signoZodiacal: "Capricórnio",
    grauAbsolutoInicio: 270,
    grauAbsolutoFim: 275,
    datas: [{ dia: 25, mes: 7 }, { dia: 6, mes: 10 }, { dia: 13, mes: 5 }, { dia: 18, mes: 12 }, { dia: 1, mes: 3 }],
    hierarquia: "Coro 7 - Principados",
    principeRegente: "Haniel.",
    daemonCorrespondente: "Orobas",
    atributo: "Deus eterno.",
    essencia: "LUCIDEZ INTELECTUAL.",
    salmo: "101",
    horario: "18:00 Ã s 18:20",
  },
  {
    numero: 56,
    nome: "Poiel",
    planeta: "Sol",
    signoZodiacal: "Capricórnio",
    grauAbsolutoInicio: 275,
    grauAbsolutoFim: 280,
    datas: [{ dia: 26, mes: 7 }, { dia: 7, mes: 10 }, { dia: 14, mes: 5 }, { dia: 19, mes: 12 }, { dia: 2, mes: 3 }],
    hierarquia: "Coro 7 - Principados",
    principeRegente: "Haniel.",
    daemonCorrespondente: "Gremory",
    atributo: "Deus que sustenta o universo.",
    essencia: "SUSTENTAÇÃO, FORTUNA, TALENTO, MODÉSTIA.",
    salmo: "144",
    horario: "18:20 Ã s 18:40",
  },
  {
    numero: 57,
    nome: "Nemamiah",
    planeta: "Marte",
    signoZodiacal: "Capricórnio",
    grauAbsolutoInicio: 280,
    grauAbsolutoFim: 285,
    datas: [{ dia: 27, mes: 7 }, { dia: 8, mes: 10 }, { dia: 15, mes: 5 }, { dia: 20, mes: 12 }, { dia: 3, mes: 3 }],
    hierarquia: "Coro 8 - Arcanjos",
    principeRegente: "Rafael.",
    daemonCorrespondente: "Ose",
    atributo: "Deus louvável.",
    essencia: "ENTENDIMENTO OU DISCERNIMENTO.",
    salmo: "113",
    horario: "18:40 Ã s 19:00",
  },
  {
    numero: 58,
    nome: "Yeialel",
    planeta: "Marte",
    signoZodiacal: "Capricórnio",
    grauAbsolutoInicio: 285,
    grauAbsolutoFim: 290,
    datas: [{ dia: 28, mes: 7 }, { dia: 9, mes: 10 }, { dia: 16, mes: 5 }, { dia: 21, mes: 12 }, { dia: 4, mes: 3 }],
    hierarquia: "Coro 8 - Arcanjos",
    principeRegente: "Rafael.",
    daemonCorrespondente: "Amy",
    atributo: "Deus que acolhe as gerações.",
    essencia: "FORTALEZA MENTAL.",
    salmo: "6",
    horario: "19:00 Ã s 19:20",
  },
  {
    numero: 59,
    nome: "Harahel",
    planeta: "Sol",
    signoZodiacal: "Capricórnio",
    grauAbsolutoInicio: 290,
    grauAbsolutoFim: 295,
    datas: [{ dia: 29, mes: 7 }, { dia: 10, mes: 10 }, { dia: 17, mes: 5 }, { dia: 22, mes: 12 }, { dia: 5, mes: 3 }],
    hierarquia: "Coro 8 - Arcanjos",
    principeRegente: "Rafael.",
    daemonCorrespondente: "Orias",
    atributo: "Deus conhecedor de todas as Coisas.",
    essencia: "RIQUEZA INTELECTUAL.",
    salmo: "112",
    horario: "19:20 Ã s 19:40",
  },
  {
    numero: 60,
    nome: "Mitsrael",
    planeta: "Lua",
    signoZodiacal: "Capricórnio",
    grauAbsolutoInicio: 295,
    grauAbsolutoFim: 300,
    datas: [{ dia: 30, mes: 7 }, { dia: 11, mes: 10 }, { dia: 18, mes: 5 }, { dia: 23, mes: 12 }, { dia: 6, mes: 3 }],
    hierarquia: "Coro 8 - Arcanjos",
    principeRegente: "Rafael.",
    daemonCorrespondente: "Vapula",
    atributo: "Deus que conforta os oprimidos.",
    essencia: "REPARAÇÃO.",
    salmo: "144",
    horario: "19:40 Ã s 20:00",
  },
  {
    numero: 61,
    nome: "Umabel",
    planeta: "VÃªnus",
    signoZodiacal: "Aquário",
    grauAbsolutoInicio: 300,
    grauAbsolutoFim: 305,
    datas: [{ dia: 31, mes: 7 }, { dia: 12, mes: 10 }, { dia: 19, mes: 5 }, { dia: 24, mes: 12 }, { dia: 7, mes: 3 }],
    hierarquia: "Coro 8 - Arcanjos",
    principeRegente: "Rafael.",
    daemonCorrespondente: "Zagan",
    atributo: "Deus acima de todas as coisas.",
    essencia: "AFINIDADE, AMIZADE, ANALOGIA.",
    salmo: "112",
    horario: "20:00 Ã s 20:20",
  },
  {
    numero: 62,
    nome: "Iah-Hel",
    planeta: "Saturno",
    signoZodiacal: "Aquário",
    grauAbsolutoInicio: 305,
    grauAbsolutoFim: 310,
    datas: [{ dia: 1, mes: 8 }, { dia: 13, mes: 10 }, { dia: 20, mes: 5 }, { dia: 25, mes: 12 }, { dia: 8, mes: 3 }],
    hierarquia: "Coro 8 - Arcanjos",
    principeRegente: "Rafael.",
    daemonCorrespondente: "Valac",
    atributo: "Ser supremo.",
    essencia: "AFÃ DE SABER.",
    salmo: "118",
    horario: "20:20 Ã s 20:40",
  },
  {
    numero: 63,
    nome: "Anauel",
    planeta: "MercÃºrio",
    signoZodiacal: "Aquário",
    grauAbsolutoInicio: 310,
    grauAbsolutoFim: 315,
    datas: [{ dia: 2, mes: 8 }, { dia: 14, mes: 10 }, { dia: 21, mes: 5 }, { dia: 26, mes: 12 }, { dia: 9, mes: 3 }],
    hierarquia: "Coro 8 - Arcanjos",
    principeRegente: "Rafael.",
    daemonCorrespondente: "Andras",
    atributo: "Deus infinitamente bom.",
    essencia: "PERCEPÇÃO DA UNIDADE.",
    salmo: "2",
    horario: "20:40 Ã s 21:00",
  },
  {
    numero: 64,
    nome: "Mehiel",
    planeta: "MercÃºrio",
    signoZodiacal: "Aquário",
    grauAbsolutoInicio: 315,
    grauAbsolutoFim: 320,
    datas: [{ dia: 3, mes: 8 }, { dia: 15, mes: 10 }, { dia: 22, mes: 5 }, { dia: 27, mes: 12 }, { dia: 10, mes: 3 }],
    hierarquia: "Coro 8 - Arcanjos",
    principeRegente: "Rafael.",
    daemonCorrespondente: "Haures",
    atributo: "Deus vivificador ou Deus que vivifica todas as coisas.",
    essencia: "VIVIFICAÇÃO.",
    salmo: "32",
    horario: "21:00 Ã s 21:20",
  },
  {
    numero: 65,
    nome: "Damabiah",
    planeta: "Lua",
    signoZodiacal: "Aquário",
    grauAbsolutoInicio: 320,
    grauAbsolutoFim: 325,
    datas: [{ dia: 4, mes: 8 }, { dia: 16, mes: 10 }, { dia: 23, mes: 5 }, { dia: 28, mes: 12 }, { dia: 11, mes: 3 }],
    hierarquia: "Coro 9 - Anjos",
    principeRegente: "Gabriel.",
    daemonCorrespondente: "Andrealphus",
    atributo: "Deus fonte de sabedoria.",
    essencia: "FONTE DE SABEDORIA.",
    salmo: "89",
    horario: "21:20 Ã s 21:40",
  },
  {
    numero: 66,
    nome: "Mamaquel",
    planeta: "Netuno",
    signoZodiacal: "Aquário",
    grauAbsolutoInicio: 325,
    grauAbsolutoFim: 330,
    datas: [{ dia: 5, mes: 8 }, { dia: 17, mes: 10 }, { dia: 24, mes: 5 }, { dia: 29, mes: 12 }, { dia: 12, mes: 3 }],
    hierarquia: "Coro 9 - Anjos",
    principeRegente: "Gabriel.",
    daemonCorrespondente: "Cimeies",
    atributo: "Deus que secunda e mantém todas as coisas.",
    essencia: "CONHECIMENTO DO BEM E DO MAL.",
    salmo: "37",
    horario: "21:40 Ã s 22:00",
  },
  {
    numero: 67,
    nome: "Ayael",
    planeta: "Saturno",
    signoZodiacal: "Peixes",
    grauAbsolutoInicio: 330,
    grauAbsolutoFim: 335,
    datas: [{ dia: 6, mes: 8 }, { dia: 18, mes: 10 }, { dia: 25, mes: 5 }, { dia: 30, mes: 12 }, { dia: 13, mes: 3 }],
    hierarquia: "Coro 9 - Anjos",
    principeRegente: "Gabriel.",
    daemonCorrespondente: "Amdusias",
    atributo: "Deus, delícia das crianças.",
    essencia: "TRANSUBSTANCIAÇÃO.",
    salmo: "36",
    horario: "22:00 Ã s 22:20",
  },
  {
    numero: 68,
    nome: "Habuiah",
    planeta: "Lua",
    signoZodiacal: "Peixes",
    grauAbsolutoInicio: 335,
    grauAbsolutoFim: 340,
    datas: [{ dia: 7, mes: 8 }, { dia: 19, mes: 10 }, { dia: 26, mes: 5 }, { dia: 31, mes: 12 }, { dia: 14, mes: 3 }],
    hierarquia: "Coro 9 - Anjos",
    principeRegente: "Gabriel.",
    daemonCorrespondente: "Belial",
    atributo: "Deus generoso, Deus que dá com liberalidade.",
    essencia: "CURA.",
    salmo: "105",
    horario: "22:20 Ã s 22:40",
  },
  {
    numero: 69,
    nome: "Rochel",
    planeta: "JÃºpiter",
    signoZodiacal: "Peixes",
    grauAbsolutoInicio: 340,
    grauAbsolutoFim: 345,
    datas: [{ dia: 8, mes: 8 }, { dia: 20, mes: 10 }, { dia: 27, mes: 5 }, { dia: 1, mes: 1 }, { dia: 15, mes: 3 }],
    hierarquia: "Coro 9 - Anjos",
    principeRegente: "Gabriel.",
    daemonCorrespondente: "Decarabia",
    atributo: "Deus que tudo Vê.",
    essencia: "RESTITUIÇÃO.",
    salmo: "15",
    horario: "22:40 Ã s 23:00",
  },
  {
    numero: 70,
    nome: "Yabamiah",
    planeta: "Sol",
    signoZodiacal: "Peixes",
    grauAbsolutoInicio: 345,
    grauAbsolutoFim: 350,
    datas: [{ dia: 9, mes: 8 }, { dia: 21, mes: 10 }, { dia: 28, mes: 5 }, { dia: 2, mes: 1 }, { dia: 16, mes: 3 }],
    hierarquia: "Coro 9 - Anjos",
    principeRegente: "Gabriel.",
    daemonCorrespondente: "Seere",
    atributo: "Verbo que produz todas as coisas.",
    essencia: "ALQUIMIA.",
    salmo: "1",
    horario: "23:00 Ã s 23:20",
  },
  {
    numero: 71,
    nome: "Haiaiel",
    planeta: "Marte",
    signoZodiacal: "Peixes",
    grauAbsolutoInicio: 350,
    grauAbsolutoFim: 355,
    datas: [{ dia: 10, mes: 8 }, { dia: 22, mes: 10 }, { dia: 29, mes: 5 }, { dia: 3, mes: 1 }, { dia: 17, mes: 3 }],
    hierarquia: "Coro 9 - Anjos",
    principeRegente: "Gabriel.",
    daemonCorrespondente: "Dantalion",
    atributo: "Deus, senhor do universo.",
    essencia: "ARMAS PARA O COMBATE.",
    salmo: "108",
    horario: "23:20 Ã s 23:40",
  },
  {
    numero: 72,
    nome: "Mumiah",
    planeta: "Netuno",
    signoZodiacal: "Peixes",
    grauAbsolutoInicio: 355,
    grauAbsolutoFim: 360,
    datas: [{ dia: 11, mes: 8 }, { dia: 23, mes: 10 }, { dia: 30, mes: 5 }, { dia: 4, mes: 1 }, { dia: 18, mes: 3 }],
    hierarquia: "Coro 9 - Anjos",
    principeRegente: "Gabriel.",
    daemonCorrespondente: "Andromalius",
    atributo: "Fim de todas as coisas.",
    essencia: "RENASCER.",
    salmo: "114",
    horario: "23:40 Ã s 00:00",
  },
];

// ─── Funções de acesso ───────────────────────────────────────────────────────

/**
 * Busca o anjo natal pelo dia e mês de nascimento.
 * Retorna null se for dia dos Gênios da Humanidade (campo especial).
 * @param {number} dia
 * @param {number} mes
 * @returns {{ anjo: object|null, ehGenio: boolean }}
 */
function buscarAnjoPorData(dia, mes) {
  const ehGenio = GENIOS_DA_HUMANIDADE.some(g => g.dia === dia && g.mes === mes);
  if (ehGenio) return { anjo: null, ehGenio: true };
  const anjo = ANJOS_DB.find(a => a.datas.some(d => d.dia === dia && d.mes === mes));
  return { anjo: anjo || null, ehGenio: false };
}

/**
 * Busca o anjo pelo grau zodiacal absoluto (para o anjo operacional).
 * Cada anjo cobre 5° — grau pertence a [grauAbsolutoInicio, grauAbsolutoFim).
 * @param {number} grauAbsoluto — 0–360°
 * @returns {object|null}
 */
function buscarAnjoPorGrau(grauAbsoluto) {
  const g = ((grauAbsoluto % 360) + 360) % 360;
  return ANJOS_DB.find(a => g >= a.grauAbsolutoInicio && g < a.grauAbsolutoFim) || null;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { ANJOS_DB, GENIOS_DA_HUMANIDADE, buscarAnjoPorData, buscarAnjoPorGrau };
}
