/**
 * daemonsDatabase.js — Banco dos 72 Daemons da Goétia · Sistema Ars Akasha
 *
 * Fonte: 05-72-daemons-goetia/01-daemons-goetia/ (fichas individuais)
 *
 * Estrutura zodiacal:
 *   36 decanatos de 10° cada (zodíaco completo de 360°).
 *   Cada decanato tem 2 daemons: um diurno (1–36) e um noturno (37–72).
 *   Mesmo grau zodiacal → daemon diferente conforme sect do mapa natal.
 */

const DAEMONS_DB = [
  {
    numero: 1,
    nome: "Baal",
    periodo: "dia",
    signo: "Aries",
    grauAbsolutoInicio: 0,
    grauAbsolutoFim: 10,
    decanato: "Marte em Aries",
    planeta: "Sol",
    poderes: "Invisibilidade, fertilidade",
    palavraChave: "Domínio",
    aspectoLuminoso: "liderança • fertilidade • soberania",
    aspectoSombrio: "tirania • orgulho • dominação",
    fraseOracular: "\"O poder invisível governa antes de ser percebido.\"",
    hierarquia: "Rei do Leste",
    anjoRelacionado: "Vehuiah",
    tarot: "2 de paus",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "rubi, diamante, ametista, cornalina, granada, magnetita, topázio",
  },
  {
    numero: 2,
    nome: "Agares",
    periodo: "dia",
    signo: "Aries",
    grauAbsolutoInicio: 10,
    grauAbsolutoFim: 20,
    decanato: "Sol em Aries",
    planeta: "Venus",
    poderes: "Rapidez, ensinar linguas, causar tremores, quebrar dignidades espirituais e temporais",
    palavraChave: "Movimento",
    aspectoLuminoso: "comunicação • rapidez • inteligência",
    aspectoSombrio: "instabilidade • manipulação • inquietação",
    fraseOracular: "\"A palavra correta move até aquilo que parecia imóvel.\"",
    hierarquia: "Duque do Leste, da ordem das Virtudes",
    anjoRelacionado: "Jeliel",
    tarot: "3 de paus",
    cores: "Verde",
    metal: "Cobre",
    pedras: "rubi, diamante, ametista, cornalina, granada, magnetita, topázio",
  },
  {
    numero: 3,
    nome: "Vassago",
    periodo: "dia",
    signo: "Aries",
    grauAbsolutoInicio: 20,
    grauAbsolutoFim: 30,
    decanato: "Venus em Aries",
    planeta: "Jupiter",
    poderes: "Conhece passado e futuro, revela o que esta oculto, incita o amor das mulheres pelos homens",
    palavraChave: "Visão",
    aspectoLuminoso: "intuição • percepção • previsão",
    aspectoSombrio: "paranoia • ilusão • ansiedade",
    fraseOracular: "\"O invisível fala antes do destino se revelar.\"",
    hierarquia: "Principe",
    anjoRelacionado: "Sitael",
    tarot: "4 de paus",
    cores: "Azul",
    metal: "Estanho",
    pedras: "rubi, diamante, ametista, cornalina, granada, magnetita, topázio",
  },
  {
    numero: 4,
    nome: "Samigina",
    periodo: "dia",
    signo: "Touro",
    grauAbsolutoInicio: 30,
    grauAbsolutoFim: 40,
    decanato: "Mercurio em Touro",
    planeta: "Lua",
    poderes: "Ensina ciencias liberais, fala sobre as almas de pecadores",
    palavraChave: "Memória",
    aspectoLuminoso: "lembrança • estudo • ancestralidade",
    aspectoSombrio: "apego • melancolia • estagnação",
    fraseOracular: "\"As vozes do passado ainda moldam o presente.\"",
    hierarquia: "Grande Marques",
    anjoRelacionado: "Elemiah",
    tarot: "5 de ouros",
    cores: "Prateado",
    metal: "Prata",
    pedras: "esmeralda, topázio, azurita, cianita, safira, turmalina, quartzo rosa",
  },
  {
    numero: 5,
    nome: "Marbas",
    periodo: "dia",
    signo: "Touro",
    grauAbsolutoInicio: 40,
    grauAbsolutoFim: 50,
    decanato: "Lua em Touro",
    planeta: "Mercurio",
    poderes: "Causar e curar doencas, ensinar mecanica, transmutacao de humanos",
    palavraChave: "Transformação",
    aspectoLuminoso: "cura • inteligência • restauração",
    aspectoSombrio: "obsessão • desgaste • desequilíbrio",
    fraseOracular: "\"Toda transformação começa pela matéria corrompida.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Mahasiah",
    tarot: "6 de ouros",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "esmeralda, topázio, azurita, cianita, safira, turmalina, quartzo rosa",
  },
  {
    numero: 6,
    nome: "Valefor",
    periodo: "dia",
    signo: "Touro",
    grauAbsolutoInicio: 50,
    grauAbsolutoFim: 60,
    decanato: "Saturno em Touro",
    planeta: "Venus",
    poderes: "Roubar e instigar pessoas a roubarem, conceder destreza, curar doencas",
    palavraChave: "Tentação",
    aspectoLuminoso: "persuasão • charme • adaptação",
    aspectoSombrio: "vício • engano • corrupção",
    fraseOracular: "\"Nem toda oferta revela seu verdadeiro preço.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Lelahel",
    tarot: "7 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "esmeralda, topázio, azurita, cianita, safira, turmalina, quartzo rosa",
  },
  {
    numero: 7,
    nome: "Amon",
    periodo: "dia",
    signo: "Gemeos",
    grauAbsolutoInicio: 60,
    grauAbsolutoFim: 70,
    decanato: "Jupiter em Gemeos",
    planeta: "Lua",
    poderes: "Conceder terras, mostrar passado e futuro, reconciliar amizades",
    palavraChave: "Reconciliação",
    aspectoLuminoso: "diplomacia • clareza • reconciliação",
    aspectoSombrio: "conflito • rancor • divisão",
    fraseOracular: "\"A verdade aproxima aquilo que o conflito separou.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Achaiah",
    tarot: "8 de espadas",
    cores: "Prateado",
    metal: "Prata",
    pedras: "turmalina, ágata, apatita, apofilita, ulexita, citrino, crisocola",
  },
  {
    numero: 8,
    nome: "Barbatos",
    periodo: "dia",
    signo: "Gemeos",
    grauAbsolutoInicio: 70,
    grauAbsolutoFim: 80,
    decanato: "Marte em Gemeos",
    planeta: "Venus",
    poderes: "Entender a voz dos animais, abrir tesouros protegidos, falar sobre o passado e o futuro, conciliar amizades, curar sentimentos feridos, influenciar pessoas poderosas",
    palavraChave: "Natureza",
    aspectoLuminoso: "percepção • harmonia • comunicação",
    aspectoSombrio: "isolamento • silêncio • afastamento",
    fraseOracular: "\"A criação revela segredos aos que sabem ouvir.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Cahetel",
    tarot: "9 de espadas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "turmalina, ágata, apatita, apofilita, ulexita, citrino, crisocola",
  },
  {
    numero: 9,
    nome: "Paimon",
    periodo: "dia",
    signo: "Gemeos",
    grauAbsolutoInicio: 80,
    grauAbsolutoFim: 90,
    decanato: "Sol em Gemeos",
    planeta: "Sol",
    poderes: "Ensinar sobre artes e ciencias, conceder familiares",
    palavraChave: "Conhecimento",
    aspectoLuminoso: "sabedoria • liderança • eloquência",
    aspectoSombrio: "arrogância • dominação • excesso",
    fraseOracular: "\"O saber exige domínio sobre si mesmo.\"",
    hierarquia: "Grande Rei do Oeste",
    anjoRelacionado: "Haziel",
    tarot: "10 de espadas",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "turmalina, ágata, apatita, apofilita, ulexita, citrino, crisocola",
  },
  {
    numero: 10,
    nome: "Buer",
    periodo: "dia",
    signo: "Cancer",
    grauAbsolutoInicio: 90,
    grauAbsolutoFim: 100,
    decanato: "Venus em Cancer",
    planeta: "Mercurio",
    poderes: "Ensinar sobre filosofia, logica e plantas, curar vicios, fornecer familiares",
    palavraChave: "Equilíbrio",
    aspectoLuminoso: "harmonia • medicina • razão",
    aspectoSombrio: "rigidez • frieza • indecisão",
    fraseOracular: "\"A ordem nasce do ajuste entre forças opostas.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Aladiah",
    tarot: "2 de copas",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "pérola, âmbar, berilo, espinélio marrom, opala, rodonita, rubi",
  },
  {
    numero: 11,
    nome: "Gusion",
    periodo: "dia",
    signo: "Cancer",
    grauAbsolutoInicio: 100,
    grauAbsolutoFim: 110,
    decanato: "Mercurio em Cancer",
    planeta: "Venus",
    poderes: "Passado, presente e futuro; (Re)conciliar amizades",
    palavraChave: "Evolução",
    aspectoLuminoso: "evolução • inteligência • clareza",
    aspectoSombrio: "manipulação • instabilidade • orgulho",
    fraseOracular: "\"O destino muda quando a consciência desperta.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Lauviah",
    tarot: "3 de copas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "pérola, âmbar, berilo, espinélio marrom, opala, rodonita, rubi",
  },
  {
    numero: 12,
    nome: "Sitri",
    periodo: "dia",
    signo: "Cancer",
    grauAbsolutoInicio: 110,
    grauAbsolutoFim: 120,
    decanato: "Lua em Cancer",
    planeta: "Jupiter",
    poderes: "Inflamar pessoas em amor, mostrar pessoas despidas",
    palavraChave: "Desejo",
    aspectoLuminoso: "magnetismo • desejo • atração",
    aspectoSombrio: "obsessão • luxúria • impulsividade",
    fraseOracular: "\"A paixão desperta aquilo que a razão tenta esconder.\"",
    hierarquia: "Principe",
    anjoRelacionado: "Hahaiah",
    tarot: "4 de copas",
    cores: "Azul",
    metal: "Estanho",
    pedras: "pérola, âmbar, berilo, espinélio marrom, opala, rodonita, rubi",
  },
  {
    numero: 13,
    nome: "Beleth",
    periodo: "dia",
    signo: "Leao",
    grauAbsolutoInicio: 120,
    grauAbsolutoFim: 130,
    decanato: "Saturno em Leao",
    planeta: "Sol",
    poderes: "Causar amor incondicional",
    palavraChave: "Devoção",
    aspectoLuminoso: "paixão • entrega • emoção",
    aspectoSombrio: "obsessão • ciúme • conflito",
    fraseOracular: "\"O amor intenso jamais permanece indiferente.\"",
    hierarquia: "Rei",
    anjoRelacionado: "Yezalel",
    tarot: "5 de paus",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "olho-de-gato, olho-de-tigre, rubi, âmbar, ônix, calcita laranja",
  },
  {
    numero: 14,
    nome: "Leraje",
    periodo: "dia",
    signo: "Leao",
    grauAbsolutoInicio: 130,
    grauAbsolutoFim: 140,
    decanato: "Jupiter em Leao",
    planeta: "Lua",
    poderes: "Influenciar batalhas, causar ou cicatrizar ferimentos",
    palavraChave: "Precisão",
    aspectoLuminoso: "estratégia • foco • coragem",
    aspectoSombrio: "agressividade • rivalidade • impulsividade",
    fraseOracular: "\"A vitória pertence àquele que mira antes de agir.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Mebahel",
    tarot: "6 de paus",
    cores: "Prateado",
    metal: "Prata",
    pedras: "olho-de-gato, olho-de-tigre, rubi, âmbar, ônix, calcita laranja",
  },
  {
    numero: 15,
    nome: "Eligos",
    periodo: "dia",
    signo: "Leao",
    grauAbsolutoInicio: 140,
    grauAbsolutoFim: 150,
    decanato: "Marte em Leao",
    planeta: "Venus",
    poderes: "Revelar segredos e falar sobre o futuro. Fornecer taticas de guerra e conquistar o amor dos senhores",
    palavraChave: "Estratégia",
    aspectoLuminoso: "liderança • visão • tática",
    aspectoSombrio: "manipulação • ambição • conflito",
    fraseOracular: "\"O futuro favorece os que compreendem a guerra invisivel.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Hariel",
    tarot: "7 de paus",
    cores: "Verde",
    metal: "Cobre",
    pedras: "olho-de-gato, olho-de-tigre, rubi, âmbar, ônix, calcita laranja",
  },
  {
    numero: 16,
    nome: "Zepar",
    periodo: "dia",
    signo: "Virgem",
    grauAbsolutoInicio: 150,
    grauAbsolutoFim: 160,
    decanato: "Sol em Virgem",
    planeta: "Venus",
    poderes: "Trazer o amor, tornar pessoas estereis, mudar aparencia fisica",
    palavraChave: "Fascínio",
    aspectoLuminoso: "atração • sedução • adaptação",
    aspectoSombrio: "ilusão • esterilidade • superficialidade",
    fraseOracular: "\"A aparência transforma aquilo que os olhos desejam enxergar.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Hakamiah",
    tarot: "8 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "peridoto, amazonita, âmbar, topázio azul, cornalina, citrino, granada, opala",
  },
  {
    numero: 17,
    nome: "Botis",
    periodo: "dia",
    signo: "Virgem",
    grauAbsolutoInicio: 160,
    grauAbsolutoFim: 170,
    decanato: "Venus em Virgem",
    planeta: "Mercurio",
    poderes: "Falar sobre o passado e o futuro, conceder reconciliacao.",
    palavraChave: "Mediação",
    aspectoLuminoso: "diplomacia • clareza • reconciliação",
    aspectoSombrio: "rancor • violência • dualidade",
    fraseOracular: "\"A reconciliação nasce quando a verdade é revelada.\"",
    hierarquia: "Presidente, Conde",
    anjoRelacionado: "Laviah",
    tarot: "9 de ouros",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "peridoto, amazonita, âmbar, topázio azul, cornalina, citrino, granada, opala",
  },
  {
    numero: 18,
    nome: "Bathin",
    periodo: "dia",
    signo: "Virgem",
    grauAbsolutoInicio: 170,
    grauAbsolutoFim: 180,
    decanato: "Mercurio em Virgem",
    planeta: "Venus",
    poderes: "Ervas e pedras preciosas, teletransporte",
    palavraChave: "Travessia",
    aspectoLuminoso: "exploração • adaptação • conhecimento",
    aspectoSombrio: "fuga • inquietação • dispersão",
    fraseOracular: "\"Toda jornada transforma quem atravessa o desconhecido.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Caliel",
    tarot: "10 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "peridoto, amazonita, âmbar, topázio azul, cornalina, citrino, granada, opala",
  },
  {
    numero: 19,
    nome: "Saleos",
    periodo: "dia",
    signo: "Libra",
    grauAbsolutoInicio: 180,
    grauAbsolutoFim: 190,
    decanato: "Lua em Libra",
    planeta: "Venus",
    poderes: "Amor, desejo sexual, fidelidade",
    palavraChave: "União",
    aspectoLuminoso: "fidelidade • afeto • estabilidade",
    aspectoSombrio: "dependência • ciúme • apego",
    fraseOracular: "\"O amor verdadeiro exige permanência diante do caos.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Leuviah",
    tarot: "2 de espadas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "safira, opala, ametrina, jade, kunzita, lápis-lazúli, topázio",
  },
  {
    numero: 20,
    nome: "Purson",
    periodo: "dia",
    signo: "Libra",
    grauAbsolutoInicio: 190,
    grauAbsolutoFim: 200,
    decanato: "Saturno em Libra",
    planeta: "Sol",
    poderes: "Controlar corpos, falar sobre o passado, o presente e o futuro, revelar segredos",
    palavraChave: "Controle",
    aspectoLuminoso: "inteligência • percepção • autoridade",
    aspectoSombrio: "manipulação • obsessão • dominação",
    fraseOracular: "\"A mente dominada pelo medo jamais enxerga a verdade.\"",
    hierarquia: "Rei",
    anjoRelacionado: "Pahaliah",
    tarot: "3 de espadas",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "safira, opala, ametrina, jade, kunzita, lápis-lazúli, topázio",
  },
  {
    numero: 21,
    nome: "Marax",
    periodo: "dia",
    signo: "Libra",
    grauAbsolutoInicio: 200,
    grauAbsolutoFim: 210,
    decanato: "Jupiter em Libra",
    planeta: "Mercurio",
    poderes: "Astronomia, ciencias liberais, ervas, pedras preciosas, conceder familiares",
    palavraChave: "Conhecimento",
    aspectoLuminoso: "sabedoria • estabilidade • aprendizado",
    aspectoSombrio: "rigidez • lentidão • materialismo",
    fraseOracular: "\"A natureza revela sabedoria aos que aprendem a observá-la.\"",
    hierarquia: "Presidente, Conde",
    anjoRelacionado: "Nelchael",
    tarot: "4 de espadas",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "safira, opala, ametrina, jade, kunzita, lápis-lazúli, topázio",
  },
  {
    numero: 22,
    nome: "Ipos",
    periodo: "dia",
    signo: "Escorpiao",
    grauAbsolutoInicio: 210,
    grauAbsolutoFim: 220,
    decanato: "Marte em Escorpiao",
    planeta: "Jupiter",
    poderes: "Confere sabedoria sobre qualquer momento no tempo, espirituosidade e audacidade",
    palavraChave: "Carisma",
    aspectoLuminoso: "carisma • coragem • sabedoria",
    aspectoSombrio: "arrogância • vaidade • impulsividade",
    fraseOracular: "\"A presença verdadeira conquista antes mesmo da palavra.\"",
    hierarquia: "Principe/Conde",
    anjoRelacionado: "Yeiayel",
    tarot: "5 de copas",
    cores: "Azul",
    metal: "Estanho",
    pedras: "topázio, malaquita, caroíta, dioptásio, esmeralda, granada",
  },
  {
    numero: 23,
    nome: "Aim",
    periodo: "dia",
    signo: "Escorpiao",
    grauAbsolutoInicio: 220,
    grauAbsolutoFim: 230,
    decanato: "Sol em Escorpiao",
    planeta: "Venus",
    poderes: "Queimar cidades e outros locais, conceder sagacidade, responder sobre assuntos privados",
    palavraChave: "Incêndio",
    aspectoLuminoso: "inteligência • criatividade • coragem",
    aspectoSombrio: "destruição • impulsividade • caos",
    fraseOracular: "\"O fogo da mente consome tudo aquilo que limita a vontade.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Melahel",
    tarot: "6 de copas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "topázio, malaquita, caroíta, dioptásio, esmeralda, granada",
  },
  {
    numero: 24,
    nome: "Naberius",
    periodo: "dia",
    signo: "Escorpiao",
    grauAbsolutoInicio: 230,
    grauAbsolutoFim: 240,
    decanato: "Venus em Escorpiao",
    planeta: "Lua",
    poderes: "Artes e ciencias, retorica, restaurar dignidades e honras",
    palavraChave: "Eloquência",
    aspectoLuminoso: "eloquência • aprendizado • honra",
    aspectoSombrio: "manipulação • orgulho • dissimulação",
    fraseOracular: "\"A palavra restaura aquilo que o tempo tentou destruir.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Haheuiah",
    tarot: "7 de copas",
    cores: "Prateado",
    metal: "Prata",
    pedras: "topázio, malaquita, caroíta, dioptásio, esmeralda, granada",
  },
  {
    numero: 25,
    nome: "Glasya-Labolas",
    periodo: "dia",
    signo: "Sagitario",
    grauAbsolutoInicio: 240,
    grauAbsolutoFim: 250,
    decanato: "Mercurio em Sagitario",
    planeta: "Mercurio",
    poderes: "Artes, ciencias, amor, assassinatos, passado e futuro, invisibilidade",
    palavraChave: "Estratégia",
    aspectoLuminoso: "estratégia • inteligência • percepção",
    aspectoSombrio: "crueldade • obsessão • destruição",
    fraseOracular: "\"O conhecimento oculto pertence aos que observam nas sombras.\"",
    hierarquia: "Presidente, Conde",
    anjoRelacionado: "Nithaiah",
    tarot: "8 de paus",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "turquesa, ametista, azurita, labradorita, espinélio, sodalita",
  },
  {
    numero: 26,
    nome: "Bune",
    periodo: "dia",
    signo: "Sagitario",
    grauAbsolutoInicio: 250,
    grauAbsolutoFim: 260,
    decanato: "Lua em Sagitario",
    planeta: "Venus",
    poderes: "Mudar os lugares dos mortos, conjurar espiritos, conceder riquezas",
    palavraChave: "Prosperidade",
    aspectoLuminoso: "abundância • comunicação espiritual • sabedoria",
    aspectoSombrio: "ganância • apego • manipulação",
    fraseOracular: "\"Os tesouros ocultos respondem àqueles que compreendem os mortos.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Haaiah",
    tarot: "9 de paus",
    cores: "Verde",
    metal: "Cobre",
    pedras: "turquesa, ametista, azurita, labradorita, espinélio, sodalita",
  },
  {
    numero: 27,
    nome: "Ronove",
    periodo: "dia",
    signo: "Sagitario",
    grauAbsolutoInicio: 260,
    grauAbsolutoFim: 270,
    decanato: "Saturno em Sagitario",
    planeta: "Marte",
    poderes: "Ensinar retorica, conceder favores de amigos ou inimigos",
    palavraChave: "Persuasão",
    aspectoLuminoso: "retórica • influência • diplomacia",
    aspectoSombrio: "manipulação • falsidade • ambição",
    fraseOracular: "\"A linguagem correta altera alianças e destinos.\"",
    hierarquia: "Marques, Conde",
    anjoRelacionado: "Yeratel",
    tarot: "10 de paus",
    cores: "Prateado",
    metal: "Prata",
    pedras: "turquesa, ametista, azurita, labradorita, espinélio, sodalita",
  },
  {
    numero: 28,
    nome: "Berith",
    periodo: "dia",
    signo: "Capricornio",
    grauAbsolutoInicio: 270,
    grauAbsolutoFim: 280,
    decanato: "Jupiter em Capricornio",
    planeta: "Venus",
    poderes: "Transformar metais em ouro, conceder dignidades, responder sobre passado, presente e futuro",
    palavraChave: "Aliança",
    aspectoLuminoso: "transformação • visão • autoridade",
    aspectoSombrio: "mentira • corrupção • orgulho",
    fraseOracular: "\"Toda transmutação exige um pacto entre vontade e matéria.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Seheiah",
    tarot: "2 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "azeviche, ônix, âmbar, fluorita, magnetita, galena",
  },
  {
    numero: 29,
    nome: "Astaroth",
    periodo: "dia",
    signo: "Capricornio",
    grauAbsolutoInicio: 280,
    grauAbsolutoFim: 290,
    decanato: "Marte em Capricornio",
    planeta: "Sol",
    poderes: "Descobrir segredos, falar sobre a queda dos espiritos, responder sobre passado, presente e futuro",
    palavraChave: "Conhecimento",
    aspectoLuminoso: "sabedoria • percepção • intuição",
    aspectoSombrio: "decadência • vaidade • manipulação",
    fraseOracular: "\"Os segredos antigos permanecem vivos sob as ruínas do tempo.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Reiyel",
    tarot: "3 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "azeviche, ônix, âmbar, fluorita, magnetita, galena",
  },
  {
    numero: 30,
    nome: "Forneus",
    periodo: "dia",
    signo: "Capricornio",
    grauAbsolutoInicio: 290,
    grauAbsolutoFim: 300,
    decanato: "Sol em Capricornio",
    planeta: "Lua",
    poderes: "Retorica, linguas e dialetos, transformar inimigos em amigos",
    palavraChave: "Diplomacia",
    aspectoLuminoso: "comunicação • inteligência • adaptação",
    aspectoSombrio: "falsidade • oportunismo • manipulação",
    fraseOracular: "\"A negociação verdadeira transforma inimigos em aliados.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Omael",
    tarot: "4 de ouros",
    cores: "Prateado",
    metal: "Prata",
    pedras: "azeviche, ônix, âmbar, fluorita, magnetita, galena",
  },
  {
    numero: 31,
    nome: "Foras",
    periodo: "dia",
    signo: "Aquario",
    grauAbsolutoInicio: 300,
    grauAbsolutoFim: 310,
    decanato: "Venus em Aquario",
    planeta: "Mercurio",
    poderes: "Conhecimentos sobre ervas, pedras preciosas, etica, logica, retorica, eloquencia, tesouros, coisas ocultas.",
    palavraChave: "Clareza",
    aspectoLuminoso: "sabedoria • lógica • eloquência",
    aspectoSombrio: "orgulho • frieza • isolamento",
    fraseOracular: "\"O conhecimento oculto pertence aos que aprendem a discernir.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Lecabel",
    tarot: "5 de espadas",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "água-marinha, ametista, âmbar, angelita, atacamita, magnetita",
  },
  {
    numero: 32,
    nome: "Asmoday",
    periodo: "dia",
    signo: "Aquario",
    grauAbsolutoInicio: 310,
    grauAbsolutoFim: 320,
    decanato: "Mercurio em Aquario",
    planeta: "Sol",
    poderes: "Aritmetica, Geometria, Astronomia, Artes Manuais",
    palavraChave: "Cálculo",
    aspectoLuminoso: "estratégia • inteligência • precisão",
    aspectoSombrio: "ira • arrogância • obsessão",
    fraseOracular: "\"Toda estrutura do universo responde à inteligência disciplinada.\"",
    hierarquia: "Rei",
    anjoRelacionado: "Vasariah",
    tarot: "6 de espadas",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "água-marinha, ametista, âmbar, angelita, atacamita, magnetita",
  },
  {
    numero: 33,
    nome: "Gaap",
    periodo: "dia",
    signo: "Aquario",
    grauAbsolutoInicio: 320,
    grauAbsolutoFim: 330,
    decanato: "Lua em Aquario",
    planeta: "Sol",
    poderes: "Causar amor e odio, ensinar filosofia e ciencias liberais, ensinar sobre consagracoes, conceder e libertar familiares",
    palavraChave: "Conexão",
    aspectoLuminoso: "espiritualidade • adaptação • mediação",
    aspectoSombrio: "manipulação • dependência • ilusão",
    fraseOracular: "\"As alianças espirituais moldam aquilo que os olhos não enxergam.\"",
    hierarquia: "Presidente, Principe",
    anjoRelacionado: "Yehuiah",
    tarot: "7 de espadas",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "água-marinha, ametista, âmbar, angelita, atacamita, magnetita",
  },
  {
    numero: 34,
    nome: "Furfur",
    periodo: "dia",
    signo: "Peixes",
    grauAbsolutoInicio: 330,
    grauAbsolutoFim: 340,
    decanato: "Saturno em Peixes",
    planeta: "Marte",
    poderes: "Responde sobre coisas secretas e divinas",
    palavraChave: "Mistério",
    aspectoLuminoso: "intuição • revelação • intensidade",
    aspectoSombrio: "caos • ilusão • impulsividade",
    fraseOracular: "\"Os segredos divinos se revelam apenas durante a tempestade.\"",
    hierarquia: "Conde",
    anjoRelacionado: "Lehahiah",
    tarot: "8 de copas",
    cores: "Vermelho",
    metal: "Ferro",
    pedras: "pedra-da-lua, ametista, água-marinha, berilo, ágata rendada azul, calcita, fluorita, turquesa",
  },
  {
    numero: 35,
    nome: "Marchosias",
    periodo: "dia",
    signo: "Peixes",
    grauAbsolutoInicio: 340,
    grauAbsolutoFim: 350,
    decanato: "Jupiter em Peixes",
    planeta: "Lua",
    poderes: "Lutar pelo magista",
    palavraChave: "Fúria",
    aspectoLuminoso: "coragem • resistência • proteção",
    aspectoSombrio: "brutalidade • agressão • destruição",
    fraseOracular: "\"A força desperta quando não existe mais recuo.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Chevakiah",
    tarot: "9 de copas",
    cores: "Prateado",
    metal: "Prata",
    pedras: "pedra-da-lua, ametista, água-marinha, berilo, ágata rendada azul, calcita, fluorita, turquesa",
  },
  {
    numero: 36,
    nome: "Stolas",
    periodo: "dia",
    signo: "Peixes",
    grauAbsolutoInicio: 350,
    grauAbsolutoFim: 360,
    decanato: "Marte em Peixes",
    planeta: "Jupiter",
    poderes: "Ensina sobre astronomia, ervas, gemas preciosas",
    palavraChave: "Sabedoria",
    aspectoLuminoso: "inteligência • observação • conhecimento espiritual",
    aspectoSombrio: "isolamento • excesso mental • distanciamento",
    fraseOracular: "\"A verdadeira visão nasce no silêncio daqueles que observam além da escuridão.\"",
    hierarquia: "Principe",
    anjoRelacionado: "Menadel",
    tarot: "10 de copas",
    cores: "Azul",
    metal: "Estanho",
    pedras: "pedra-da-lua, ametista, água-marinha, berilo, ágata rendada azul, calcita, fluorita, turquesa",
  },
  {
    numero: 37,
    nome: "Phenex",
    periodo: "noite",
    signo: "Aries",
    grauAbsolutoInicio: 0,
    grauAbsolutoFim: 10,
    decanato: "Marte em Aries",
    planeta: "Lua",
    poderes: "Fala sobre todas as Ciencias e sobre Poesia",
    palavraChave: "Renascimento",
    aspectoLuminoso: "criatividade • inspiração • renovação",
    aspectoSombrio: "vaidade • instabilidade • excesso imaginativo",
    fraseOracular: "\"Toda chama que consome também prepara o retorno daquilo que renasce.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Aniel",
    tarot: "2 de paus",
    cores: "Prateado",
    metal: "Prata",
    pedras: "rubi, diamante, ametista, cornalina, granada, magnetita, topázio",
  },
  {
    numero: 38,
    nome: "Halphas",
    periodo: "noite",
    signo: "Aries",
    grauAbsolutoInicio: 10,
    grauAbsolutoFim: 20,
    decanato: "Sol em Aries",
    planeta: "Marte",
    poderes: "Constroi torres e fornece guerreiros",
    palavraChave: "Fortaleza",
    aspectoLuminoso: "segurança • estratégia • resistência",
    aspectoSombrio: "paranoia • isolamento • militarização",
    fraseOracular: "\"A verdadeira proteção nasce daquilo que se constrói antes da guerra.\"",
    hierarquia: "Conde",
    anjoRelacionado: "Haamiah",
    tarot: "3 de paus",
    cores: "Vermelho",
    metal: "Ferro",
    pedras: "rubi, diamante, ametista, cornalina, granada, magnetita, topázio",
  },
  {
    numero: 39,
    nome: "Malphas",
    periodo: "noite",
    signo: "Aries",
    grauAbsolutoInicio: 20,
    grauAbsolutoFim: 30,
    decanato: "Venus em Aries",
    planeta: "Mercurio",
    poderes: "Requer sacrificios, fornece casas e torres elevadas, concede familiares, e revela os pensamentos do inimigo.",
    palavraChave: "Ocultação",
    aspectoLuminoso: "vigilância • estratégia • percepção",
    aspectoSombrio: "traição • paranoia • manipulação",
    fraseOracular: "\"Aquilo que se esconde nas sombras também observa em silêncio.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Rehael",
    tarot: "4 de paus",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "rubi, diamante, ametista, cornalina, granada, magnetita, topázio",
  },
  {
    numero: 40,
    nome: "Raum",
    periodo: "noite",
    signo: "Touro",
    grauAbsolutoInicio: 30,
    grauAbsolutoFim: 40,
    decanato: "Mercurio em Touro",
    planeta: "Marte",
    poderes: "Roubar tesouros, destruir cidades e dignidades, causar amor entre amigos e inimigos",
    palavraChave: "Ruptura",
    aspectoLuminoso: "transformação • libertação • reconstrução",
    aspectoSombrio: "caos • devastação • instabilidade",
    fraseOracular: "\"Toda destruição abre espaço para aquilo que insiste em renascer.\"",
    hierarquia: "Conde",
    anjoRelacionado: "Yeiazel",
    tarot: "5 de ouros",
    cores: "Vermelho",
    metal: "Ferro",
    pedras: "esmeralda, topázio, azurita, cianita, safira, turmalina, quartzo rosa",
  },
  {
    numero: 41,
    nome: "Focalor",
    periodo: "noite",
    signo: "Touro",
    grauAbsolutoInicio: 40,
    grauAbsolutoFim: 50,
    decanato: "Lua em Touro",
    planeta: "Venus",
    poderes: "Derrubar homens de navios, comandar mares e ventos, formar tempestades",
    palavraChave: "Tempestade",
    aspectoLuminoso: "liberdade • adaptação • movimento",
    aspectoSombrio: "caos emocional • destruição • instabilidade",
    fraseOracular: "\"As forças que movem os mares também transformam aquilo que permanece imóvel.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Hahahel",
    tarot: "6 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "esmeralda, topázio, azurita, cianita, safira, turmalina, quartzo rosa",
  },
  {
    numero: 42,
    nome: "Vepar",
    periodo: "noite",
    signo: "Touro",
    grauAbsolutoInicio: 50,
    grauAbsolutoFim: 60,
    decanato: "Saturno em Touro",
    planeta: "Venus",
    poderes: "Governa as aguas, guia navios de guerra, oculta navios, causa tempestades, variola e bexigas putrefatas.",
    palavraChave: "Profundezas",
    aspectoLuminoso: "intuição • sensibilidade • adaptação",
    aspectoSombrio: "decadência • corrupção • destruição silenciosa",
    fraseOracular: "\"Aquilo que repousa sob as águas raramente permanece adormecido.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Mikhael",
    tarot: "7 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "esmeralda, topázio, azurita, cianita, safira, turmalina, quartzo rosa",
  },
  {
    numero: 43,
    nome: "Sabnock",
    periodo: "noite",
    signo: "Gemeos",
    grauAbsolutoInicio: 60,
    grauAbsolutoFim: 70,
    decanato: "Jupiter em Gemeos",
    planeta: "Lua",
    poderes: "Construir torres, castelos e cidades, fornecer armas, causar feridas, fornecer familiares",
    palavraChave: "Fortificação",
    aspectoLuminoso: "disciplina • proteção • resistência",
    aspectoSombrio: "violência • rigidez • destruição",
    fraseOracular: "\"Toda proteção exige força para sustentar aquilo que se deseja preservar.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Veuliah",
    tarot: "8 de espadas",
    cores: "Prateado",
    metal: "Prata",
    pedras: "turmalina, ágata, apatita, apofilita, ulexita, citrino, crisocola",
  },
  {
    numero: 44,
    nome: "Shax",
    periodo: "noite",
    signo: "Gemeos",
    grauAbsolutoInicio: 70,
    grauAbsolutoFim: 80,
    decanato: "Marte em Gemeos",
    planeta: "Venus",
    poderes: "Esvair o entendimento e a inteligencia, entrar em recintos fechados, conceder cavalos, revelar coisas ocultas, conceder familiares",
    palavraChave: "Esquecimento",
    aspectoLuminoso: "desapego • discrição • percepção",
    aspectoSombrio: "alienação • confusão • perda mental",
    fraseOracular: "\"Aquilo que se perde na memória ainda permanece oculto nas sombras.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Yelahiah",
    tarot: "9 de espadas",
    cores: "Prateado",
    metal: "Prata",
    pedras: "turmalina, ágata, apatita, apofilita, ulexita, citrino, crisocola",
  },
  {
    numero: 45,
    nome: "Vine",
    periodo: "noite",
    signo: "Gemeos",
    grauAbsolutoInicio: 80,
    grauAbsolutoFim: 90,
    decanato: "Sol em Gemeos",
    planeta: "Sol",
    poderes: "Descobrir coisas escondidas, revelar bruxas, construir torres, derrubar muralhas, causar tempestades",
    palavraChave: "Poder",
    aspectoLuminoso: "força • revelação • proteção",
    aspectoSombrio: "tirania • agressividade • destruição",
    fraseOracular: "\"A força que derruba muralhas também revela aquilo que estava oculto.\"",
    hierarquia: "Rei, Conde",
    anjoRelacionado: "Sehaliah",
    tarot: "10 de espadas",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "turmalina, ágata, apatita, apofilita, ulexita, citrino, crisocola",
  },
  {
    numero: 46,
    nome: "Bifrons",
    periodo: "noite",
    signo: "Cancer",
    grauAbsolutoInicio: 90,
    grauAbsolutoFim: 100,
    decanato: "Venus em Cancer",
    planeta: "Marte",
    poderes: "Astrologia, Geometria, Artes, pedras e madeiras, mover e sinalizar cadaveres",
    palavraChave: "Travessia",
    aspectoLuminoso: "transformação • sabedoria • percepção espiritual",
    aspectoSombrio: "morbidez • frieza • apego",
    fraseOracular: "\"Aquele que compreende os mortos aprende a enxergar além do tempo.\"",
    hierarquia: "Conde",
    anjoRelacionado: "Ariel",
    tarot: "2 de copas",
    cores: "Vermelho",
    metal: "Ferro",
    pedras: "pérola, âmbar, berilo, espinélio marrom, opala, rodonita, rubi",
  },
  {
    numero: 47,
    nome: "Vual",
    periodo: "noite",
    signo: "Cancer",
    grauAbsolutoInicio: 100,
    grauAbsolutoFim: 110,
    decanato: "Mercurio em Cancer",
    planeta: "Venus",
    poderes: "Amor, amizade entre amigos e inimigos",
    palavraChave: "Conciliação",
    aspectoLuminoso: "empatia • harmonia • diplomacia",
    aspectoSombrio: "submissão • dependência • tensão",
    fraseOracular: "\"Os caminhos mais difíceis se tornam possíveis quando há disposição para unir.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Asaliah",
    tarot: "3 de copas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "pérola, âmbar, berilo, espinélio marrom, opala, rodonita, rubi",
  },
  {
    numero: 48,
    nome: "Hagenti",
    periodo: "noite",
    signo: "Cancer",
    grauAbsolutoInicio: 110,
    grauAbsolutoFim: 120,
    decanato: "Lua em Cancer",
    planeta: "Mercurio",
    poderes: "Transmutar metais em ouro, transformar agua em vinho e vice-versa",
    palavraChave: "Alquimia",
    aspectoLuminoso: "refinamento • transformação • adaptação",
    aspectoSombrio: "corrupção • ganância • instabilidade",
    fraseOracular: "\"A verdadeira transformação ocorre quando a essência muda junto da forma.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Mihael",
    tarot: "4 de copas",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "pérola, âmbar, berilo, espinélio marrom, opala, rodonita, rubi",
  },
  {
    numero: 49,
    nome: "Crocell",
    periodo: "noite",
    signo: "Leao",
    grauAbsolutoInicio: 120,
    grauAbsolutoFim: 130,
    decanato: "Saturno em Leao",
    planeta: "Venus",
    poderes: "Revela coisas ocultas, ensina geometria, ciencias liberais, rege as tormentas e produz rumor de aguas. Comanda termas e banhos quentes.",
    palavraChave: "Fluxo",
    aspectoLuminoso: "serenidade • intuição • percepção",
    aspectoSombrio: "dispersão • instabilidade • ocultamento",
    fraseOracular: "\"As águas revelam aquilo que o silêncio tentou esconder.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Vehuel",
    tarot: "5 de paus",
    cores: "Verde",
    metal: "Cobre",
    pedras: "olho-de-gato, olho-de-tigre, rubi, âmbar, ônix, calcita laranja",
  },
  {
    numero: 50,
    nome: "Furcas",
    periodo: "noite",
    signo: "Leao",
    grauAbsolutoInicio: 130,
    grauAbsolutoFim: 140,
    decanato: "Jupiter em Leao",
    planeta: "Saturno ou Venus",
    poderes: "Filosofia, Astrologia, Retorica, Logica, Quiromancia e Piromancia",
    palavraChave: "Iniciação",
    aspectoLuminoso: "sabedoria • disciplina • profundidade",
    aspectoSombrio: "isolamento • obsessão • rigidez",
    fraseOracular: "\"O verdadeiro conhecimento exige atravessar aquilo que os outros temem compreender.\"",
    hierarquia: "Cavaleiro ou Duque",
    anjoRelacionado: "Daniel",
    tarot: "6 de paus",
    cores: "Preto",
    metal: "Chumbo",
    pedras: "olho-de-gato, olho-de-tigre, rubi, âmbar, ônix, calcita laranja",
  },
  {
    numero: 51,
    nome: "Balam",
    periodo: "noite",
    signo: "Leao",
    grauAbsolutoInicio: 140,
    grauAbsolutoFim: 150,
    decanato: "Marte em Leao",
    planeta: "Sol",
    poderes: "Sagacidade, invisibilidade, responder sobre o passado, o presente e o futuro",
    palavraChave: "Visão",
    aspectoLuminoso: "percepção • clarividência • inteligência",
    aspectoSombrio: "paranoia • isolamento • manipulação",
    fraseOracular: "\"Aquele que observa além das aparências jamais será surpreendido pelo destino.\"",
    hierarquia: "Rei",
    anjoRelacionado: "Hahasiah",
    tarot: "7 de paus",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "olho-de-gato, olho-de-tigre, rubi, âmbar, ônix, calcita laranja",
  },
  {
    numero: 52,
    nome: "Alloces",
    periodo: "noite",
    signo: "Virgem",
    grauAbsolutoInicio: 150,
    grauAbsolutoFim: 160,
    decanato: "Sol em Virgem",
    planeta: "Venus",
    poderes: "Astronomia, ciencias liberais, fornecer familiares",
    palavraChave: "Precisão",
    aspectoLuminoso: "disciplina • inteligência • organização",
    aspectoSombrio: "frieza • obsessão • rigidez",
    fraseOracular: "\"A verdadeira ordem nasce quando a mente aprende a dominar o caos.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Imamiah",
    tarot: "8 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "peridoto, amazonita, âmbar, topázio azul, cornalina, citrino, granada, opala",
  },
  {
    numero: 53,
    nome: "Camio",
    periodo: "noite",
    signo: "Virgem",
    grauAbsolutoInicio: 160,
    grauAbsolutoFim: 170,
    decanato: "Venus em Virgem",
    planeta: "Mercurio",
    poderes: "Ensinar sobre passaros, touros, caes e sobre os sons das aguas, responder sobre o futuro",
    palavraChave: "Interpretação",
    aspectoLuminoso: "intuição • percepção • comunicação espiritual",
    aspectoSombrio: "impulsividade • confusão • instabilidade",
    fraseOracular: "\"A natureza sempre comunica aquilo que o homem esqueceu de ouvir.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Nanael",
    tarot: "9 de ouros",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "peridoto, amazonita, âmbar, topázio azul, cornalina, citrino, granada, opala",
  },
  {
    numero: 54,
    nome: "Murmur",
    periodo: "noite",
    signo: "Virgem",
    grauAbsolutoInicio: 170,
    grauAbsolutoFim: 180,
    decanato: "Mercurio em Virgem",
    planeta: "Venus",
    poderes: "Filosofia, conversar com almas falecidas",
    palavraChave: "Memória",
    aspectoLuminoso: "sabedoria ancestral • reflexão • conexão espiritual",
    aspectoSombrio: "melancolia • apego • obsessão espiritual",
    fraseOracular: "\"Os ecos dos mortos continuam vivos naquilo que o tempo não consegue apagar.\"",
    hierarquia: "Duque, Conde",
    anjoRelacionado: "Nithael",
    tarot: "10 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "peridoto, amazonita, âmbar, topázio azul, cornalina, citrino, granada, opala",
  },
  {
    numero: 55,
    nome: "Orobas",
    periodo: "noite",
    signo: "Libra",
    grauAbsolutoInicio: 180,
    grauAbsolutoFim: 190,
    decanato: "Lua em Libra",
    planeta: "Jupiter",
    poderes: "Fornecer dignidades e favores, responder sobre divindades e teologia",
    palavraChave: "Honra",
    aspectoLuminoso: "integridade • lealdade • sabedoria espiritual",
    aspectoSombrio: "orgulho • rigidez • moralismo",
    fraseOracular: "\"A verdadeira dignidade nasce daquilo que permanece íntegro diante do poder.\"",
    hierarquia: "Principe",
    anjoRelacionado: "Mebahiah",
    tarot: "2 de espadas",
    cores: "Azul",
    metal: "Estanho",
    pedras: "safira, opala, ametrina, jade, kunzita, lápis-lazúli, topázio",
  },
  {
    numero: 56,
    nome: "Gremory",
    periodo: "noite",
    signo: "Libra",
    grauAbsolutoInicio: 190,
    grauAbsolutoFim: 200,
    decanato: "Saturno em Libra",
    planeta: "Venus",
    poderes: "Encontrar tesouros, trazer o amor de mulheres, falar sobre passado, presente e futuro",
    palavraChave: "Encantamento",
    aspectoLuminoso: "magnetismo • atração • intuição",
    aspectoSombrio: "obsessão • ilusão • manipulação emocional",
    fraseOracular: "\"Os tesouros mais profundos raramente se revelam sem fascínio e desejo.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Poyel",
    tarot: "3 de espadas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "safira, opala, ametrina, jade, kunzita, lápis-lazúli, topázio",
  },
  {
    numero: 57,
    nome: "Ose",
    periodo: "noite",
    signo: "Libra",
    grauAbsolutoInicio: 200,
    grauAbsolutoFim: 210,
    decanato: "Jupiter em Libra",
    planeta: "Mercurio",
    poderes: "Mudar a forma dos homens, responder sobre divindades e coisas secretas, ciencias liberais",
    palavraChave: "Metamorfose",
    aspectoLuminoso: "adaptação • criatividade • percepção",
    aspectoSombrio: "ilusão • dissimulação • perda de identidade",
    fraseOracular: "\"Toda máscara revela algo sobre aquilo que tenta esconder.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Nemamiah",
    tarot: "4 de espadas",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "safira, opala, ametrina, jade, kunzita, lápis-lazúli, topázio",
  },
  {
    numero: 58,
    nome: "Amy",
    periodo: "noite",
    signo: "Escorpiao",
    grauAbsolutoInicio: 210,
    grauAbsolutoFim: 220,
    decanato: "Marte em Escorpiao",
    planeta: "Mercurio",
    poderes: "Astrologia, ciencias liberais, fornecer familiares, roubar tesouros protegidos",
    palavraChave: "Iluminação",
    aspectoLuminoso: "inteligência • descoberta • inspiração",
    aspectoSombrio: "ganância • obsessão • destruição",
    fraseOracular: "\"O fogo do conhecimento revela riquezas ocultas aos que suportam sua intensidade.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Yeialel",
    tarot: "5 de copas",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "topázio, malaquita, caroíta, dioptásio, esmeralda, granada",
  },
  {
    numero: 59,
    nome: "Orias",
    periodo: "noite",
    signo: "Escorpiao",
    grauAbsolutoInicio: 220,
    grauAbsolutoFim: 230,
    decanato: "Sol em Escorpiao",
    planeta: "Lua",
    poderes: "Poderes das estrelas e planetas, conceder favores, transformar os homens, fornecer dignidades",
    palavraChave: "Influência",
    aspectoLuminoso: "liderança • sabedoria cósmica • transformação",
    aspectoSombrio: "orgulho • manipulação • ambição",
    fraseOracular: "\"Aquele que compreende os céus aprende a transformar o próprio destino.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Harahel",
    tarot: "6 de copas",
    cores: "Prateado",
    metal: "Prata",
    pedras: "topázio, malaquita, caroíta, dioptásio, esmeralda, granada",
  },
  {
    numero: 60,
    nome: "Vapula",
    periodo: "noite",
    signo: "Escorpiao",
    grauAbsolutoInicio: 230,
    grauAbsolutoFim: 240,
    decanato: "Venus em Escorpiao",
    planeta: "Venus",
    poderes: "Ensinar artificios e profissoes, filosofia e outras ciencias",
    palavraChave: "Domínio",
    aspectoLuminoso: "criatividade • aperfeiçoamento • inteligência prática",
    aspectoSombrio: "arrogância • manipulação • frieza",
    fraseOracular: "\"O verdadeiro conhecimento transforma habilidade em poder consciente.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Mitzrael",
    tarot: "7 de copas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "topázio, malaquita, caroíta, dioptásio, esmeralda, granada",
  },
  {
    numero: 61,
    nome: "Zagan",
    periodo: "noite",
    signo: "Sagitario",
    grauAbsolutoInicio: 240,
    grauAbsolutoFim: 250,
    decanato: "Mercurio em Sagitario",
    planeta: "Sol",
    poderes: "Esperteza, transformar agua e sangue em vinho, transformar metais em dinheiro",
    palavraChave: "Alquimia",
    aspectoLuminoso: "prosperidade • adaptação • inteligência",
    aspectoSombrio: "corrupção • ganância • manipulação",
    fraseOracular: "\"Toda matéria muda quando a vontade aprende a dominar sua essência.\"",
    hierarquia: "Rei, Presidente",
    anjoRelacionado: "Umabel",
    tarot: "8 de paus",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "turquesa, ametista, azurita, labradorita, espinélio, sodalita",
  },
  {
    numero: 62,
    nome: "Valac",
    periodo: "noite",
    signo: "Sagitario",
    grauAbsolutoInicio: 250,
    grauAbsolutoFim: 260,
    decanato: "Lua em Sagitario",
    planeta: "Mercurio",
    poderes: "Responder sobre tesouros escondidos, localizar e trazer serpentes",
    palavraChave: "Descoberta",
    aspectoLuminoso: "curiosidade • inteligência • percepção",
    aspectoSombrio: "obsessão • perigo • manipulação",
    fraseOracular: "\"Os maiores segredos repousam onde poucos têm coragem de procurar.\"",
    hierarquia: "Presidente",
    anjoRelacionado: "Iahel",
    tarot: "9 de paus",
    cores: "Laranja",
    metal: "Mercúrio",
    pedras: "turquesa, ametista, azurita, labradorita, espinélio, sodalita",
  },
  {
    numero: 63,
    nome: "Andras",
    periodo: "noite",
    signo: "Sagitario",
    grauAbsolutoInicio: 260,
    grauAbsolutoFim: 270,
    decanato: "Saturno em Sagitario",
    planeta: "Lua",
    poderes: "Espalhar a discordia",
    palavraChave: "Conflito",
    aspectoLuminoso: "independência • coragem • ruptura",
    aspectoSombrio: "violência • caos • destruição",
    fraseOracular: "\"A desordem cresce quando a espada supera a compreensão.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Anauel",
    tarot: "10 de paus",
    cores: "Prateado",
    metal: "Prata",
    pedras: "turquesa, ametista, azurita, labradorita, espinélio, sodalita",
  },
  {
    numero: 64,
    nome: "Haures",
    periodo: "noite",
    signo: "Capricornio",
    grauAbsolutoInicio: 270,
    grauAbsolutoFim: 280,
    decanato: "Jupiter em Capricornio",
    planeta: "Venus",
    poderes: "Falar sobre divindades, criacao do mundo e queda dos espiritos, queimar inimigos, causar tentacoes",
    palavraChave: "Revelação",
    aspectoLuminoso: "percepção espiritual • força interior • clareza",
    aspectoSombrio: "orgulho • destruição • tentação",
    fraseOracular: "\"A verdade divina pode iluminar ou consumir aqueles que a contemplam.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Mehiel",
    tarot: "2 de ouros",
    cores: "Verde",
    metal: "Cobre",
    pedras: "azeviche, ônix, âmbar, fluorita, magnetita, galena",
  },
  {
    numero: 65,
    nome: "Andrealphus",
    periodo: "noite",
    signo: "Capricornio",
    grauAbsolutoInicio: 280,
    grauAbsolutoFim: 290,
    decanato: "Marte em Capricornio",
    planeta: "Lua",
    poderes: "Transformar homens em passaros, ensinar geometria, mensuracao e astronomia",
    palavraChave: "Mensuração",
    aspectoLuminoso: "percepção cósmica • sabedoria • expansão mental",
    aspectoSombrio: "vaidade • distanciamento • orgulho intelectual",
    fraseOracular: "\"Aquele que compreende as medidas do universo aprende a enxergar além das aparências.\"",
    hierarquia: "Marques do Leste",
    anjoRelacionado: "Damabiah",
    tarot: "3 de ouros",
    cores: "Prateado",
    metal: "Prata",
    pedras: "azeviche, ônix, âmbar, fluorita, magnetita, galena",
  },
  {
    numero: 66,
    nome: "Cimeies",
    periodo: "noite",
    signo: "Capricornio",
    grauAbsolutoInicio: 290,
    grauAbsolutoFim: 300,
    decanato: "Sol em Capricornio",
    planeta: "Lua",
    poderes: "Gramatica, logica, retorica, descobrir tesouros e coisas escondidas ou perdidas, fazer homens parecerem soldados",
    palavraChave: "Estratégia",
    aspectoLuminoso: "disciplina • inteligência • percepção",
    aspectoSombrio: "frieza • manipulação • ocultamento",
    fraseOracular: "\"Os maiores segredos pertencem àqueles que sabem observar em silêncio.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Manakel",
    tarot: "4 de ouros",
    cores: "Prateado",
    metal: "Prata",
    pedras: "azeviche, ônix, âmbar, fluorita, magnetita, galena",
  },
  {
    numero: 67,
    nome: "Amdusias",
    periodo: "noite",
    signo: "Aquario",
    grauAbsolutoInicio: 300,
    grauAbsolutoFim: 310,
    decanato: "Venus em Aquario",
    planeta: "Venus",
    poderes: "Inclina e curva arvores, fornece bons familiares",
    palavraChave: "Harmonia",
    aspectoLuminoso: "sintonia • inspiração • conexão espiritual",
    aspectoSombrio: "escapismo • dispersão • instabilidade",
    fraseOracular: "\"A natureza responde àqueles que aprendem a vibrar em sintonia com suas forças.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Eyael",
    tarot: "5 de espadas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "água-marinha, ametista, âmbar, angelita, atacamita, magnetita",
  },
  {
    numero: 68,
    nome: "Belial",
    periodo: "noite",
    signo: "Aquario",
    grauAbsolutoInicio: 310,
    grauAbsolutoFim: 320,
    decanato: "Mercurio em Aquario",
    planeta: "Sol",
    poderes: "Distribui cargos, faz com que amigos ou inimigos facam favores, concede familiares.",
    palavraChave: "Influência",
    aspectoLuminoso: "carisma • liderança • diplomacia",
    aspectoSombrio: "corrupção • manipulação • ambição",
    fraseOracular: "\"A palavra certa pode abrir portas que a força jamais conseguiria mover.\"",
    hierarquia: "Rei",
    anjoRelacionado: "Habuhiah",
    tarot: "6 de espadas",
    cores: "Dourado",
    metal: "Ouro",
    pedras: "água-marinha, ametista, âmbar, angelita, atacamita, magnetita",
  },
  {
    numero: 69,
    nome: "Decarabia",
    periodo: "noite",
    signo: "Aquario",
    grauAbsolutoInicio: 320,
    grauAbsolutoFim: 330,
    decanato: "Lua em Aquario",
    planeta: "Sol",
    poderes: "Virtudes dos passaros e das pedras preciosas, gerar ilusoes de passaros",
    palavraChave: "Ilusão",
    aspectoLuminoso: "imaginação • criatividade • percepção",
    aspectoSombrio: "confusão • engano • distorção",
    fraseOracular: "\"Nem toda visão pertence ao mundo material que os olhos acreditam enxergar.\"",
    hierarquia: "Marques",
    anjoRelacionado: "Rochel",
    tarot: "7 de espadas",
    cores: "Prateado",
    metal: "Prata",
    pedras: "água-marinha, ametista, âmbar, angelita, atacamita, magnetita",
  },
  {
    numero: 70,
    nome: "Seere",
    periodo: "noite",
    signo: "Peixes",
    grauAbsolutoInicio: 330,
    grauAbsolutoFim: 340,
    decanato: "Saturno em Peixes",
    planeta: "Jupiter",
    poderes: "Trazer coisas ate o magista, revelar tesouros e coisas roubadas",
    palavraChave: "Travessia",
    aspectoLuminoso: "liberdade • agilidade • descoberta",
    aspectoSombrio: "dispersão • impulsividade • instabilidade",
    fraseOracular: "\"Nenhuma distância permanece impossível para aquele que domina os caminhos invisíveis.\"",
    hierarquia: "Principe",
    anjoRelacionado: "Jabamiah",
    tarot: "8 de copas",
    cores: "Azul",
    metal: "Estanho",
    pedras: "pedra-da-lua, ametista, água-marinha, berilo, ágata rendada azul, calcita, fluorita, turquesa",
  },
  {
    numero: 71,
    nome: "Dantalion",
    periodo: "noite",
    signo: "Peixes",
    grauAbsolutoInicio: 340,
    grauAbsolutoFim: 350,
    decanato: "Jupiter em Peixes",
    planeta: "Venus",
    poderes: "Ensinar todas as artes e ciencias, causar o amor e mostrar pessoas",
    palavraChave: "Mente",
    aspectoLuminoso: "criatividade • compreensão humana • inteligência emocional",
    aspectoSombrio: "manipulação • confusão • perda de identidade",
    fraseOracular: "\"Cada rosto revela uma verdade diferente dentro do mesmo espírito.\"",
    hierarquia: "Duque",
    anjoRelacionado: "Haiyael",
    tarot: "9 de copas",
    cores: "Verde",
    metal: "Cobre",
    pedras: "pedra-da-lua, ametista, água-marinha, berilo, ágata rendada azul, calcita, fluorita, turquesa",
  },
  {
    numero: 72,
    nome: "Andromalius",
    periodo: "noite",
    signo: "Peixes",
    grauAbsolutoInicio: 350,
    grauAbsolutoFim: 360,
    decanato: "Marte em Peixes",
    planeta: "Marte",
    poderes: "Trazer ladroes e coisas roubadas, descobrir e punir homens maldosos",
    palavraChave: "Justiça",
    aspectoLuminoso: "justiça • proteção • revelação",
    aspectoSombrio: "vingança • perseguição • obsessão",
    fraseOracular: "\"Aquilo que foi ocultado pelas sombras inevitavelmente retorna à luz.\"",
    hierarquia: "Conde",
    anjoRelacionado: "Mumiah",
    tarot: "10 de copas",
    cores: "Vermelho",
    metal: "Ferro",
    pedras: "pedra-da-lua, ametista, água-marinha, berilo, ágata rendada azul, calcita, fluorita, turquesa",
  },
];

// ─── Funções de acesso ───────────────────────────────────────────────────────

/**
 * Busca o daemon pelo grau zodiacal absoluto e sect (diurno/noturno).
 * @param {number}  grauAbsoluto — 0–360°
 * @param {boolean} diurno — true = diurno, false = noturno
 * @returns {object|null}
 */
function buscarDaemonPorGrau(grauAbsoluto, diurno) {
  const g = ((grauAbsoluto % 360) + 360) % 360;
  const periodo = diurno ? 'dia' : 'noite';
  return DAEMONS_DB.find(d =>
    d.periodo === periodo &&
    g >= d.grauAbsolutoInicio &&
    g < d.grauAbsolutoFim
  ) || null;
}

/**
 * Busca o daemon diurno correspondente ao mesmo grau do daemon noturno (e vice-versa).
 * Útil para a regra de não-repetição.
 * @param {object} daemon
 * @returns {object|null}
 */
function buscarParDaemon(daemon) {
  const periodoOposto = daemon.periodo === 'dia' ? 'noite' : 'dia';
  return DAEMONS_DB.find(d =>
    d.periodo === periodoOposto &&
    d.grauAbsolutoInicio === daemon.grauAbsolutoInicio
  ) || null;
}

if (typeof module !== 'undefined' && module.exports) {
  module.exports = { DAEMONS_DB, buscarDaemonPorGrau, buscarParDaemon };
}
